export { fetchApi, clearStoredTokens, getJwtExpMs } from './core';
export type { ApiResponse, TaxInfo } from './core';

export { register, login, refreshToken } from './auth';

export {
  getPlayer,
  updatePlayerSettings,
  updateTutorialStep,
  getPlayerAttributes,
  allocatePlayerAttribute,
  getSkills,
  getEquipment,
  getBestiary,
  getTurns,
  spendTurns,
  getHpState,
  restEstimate,
  rest,
  recoverFromKnockout,
} from './player';
export type { PlayerSettings } from './player';

export {
  getZones,
  travelToZone,
  estimateExploration,
  startExploration,
  startCombat,
  startCombatFromEncounterSite,
  getEncounterSites,
  selectSiteStrategy,
  abandonEncounterSites,
  getCombatLog,
  getCombatLogs,
  getEncounterSiteFights,
} from './combat';
export type {
  EventModifierBadge,
  CombatActiveEvent,
  CombatLogEntryResponse,
  SkillXpGrantResponse,
  CombatOutcomeResponse,
  CombatSourceResponse,
  CombatResultResponse,
  CombatFightResult,
  CombatResponse,
  CombatHistoryListItemResponse,
  CombatHistoryResponse,
  CombatHistoryQuery,
  EncounterSitesQuery,
  EncounterSitesResponse,
  EncounterSiteFightSummary,
  EncounterSiteFightsResponse,
} from './combat';

export {
  getInventory,
  destroyInventoryItem,
  useItem,
  repairItem,
  repairAllEquipped,
  equip,
  unequip,
  getGatheringNodes,
  mine,
  getCraftingRecipes,
  craft,
  salvage,
  salvageBatch,
  forgeUpgrade,
  forgeReroll,
  sellItem,
  sellBulk,
  getStash,
  depositToStash,
  depositBatchToStash,
  withdrawFromStash,
  withdrawBatchFromStash,
  claimLoot,
  fetchPendingLoot,
} from './items';
export type {
  PendingLootItem,
  GatheringNodesQuery,
  GatheringNodesResponse,
  InventoryItem,
  InventoryItemTemplate,
} from './items';

export {
  getPvpRating,
  getPvpLadder,
  scoutPvpOpponent,
  challengePvpOpponent,
  getPvpMatchDetail,
  getPvpHistory,
  getPvpNotifications,
  getPvpNotificationCount,
  markPvpNotificationsRead,
  getChatHistory,
  getActiveEvents,
  getZoneEvents,
  getActiveBossEncounters,
  getBossEncounter,
  signUpForBoss,
  getBossHistory,
  getAchievements,
  getAchievementUnclaimedCount,
  claimAchievementReward,
  getActiveTitle,
  setActiveTitle,
  getLeaderboardCategories,
  getLeaderboard,
} from './social';
export type {
  PvpRatingResponse,
  PvpLadderEntry,
  PvpLadderResponse,
  PvpScoutData,
  PvpMatchResponse,
  PvpChallengeResponse,
  PvpMatchDetailResponse,
  PvpNotification,
  WorldEventResponse,
  BossPlayerReward,
  BossRoundSummary,
  BossEncounterResponse,
  BossParticipantResponse,
  BossHistoryEntry,
  AchievementRewardResponse,
  PlayerAchievementProgress,
  AchievementsResponse,
  LeaderboardEntry,
  LeaderboardResponse,
  LeaderboardCategoryGroup,
  LeaderboardCategoriesResponse,
} from './social';

export { getResources } from './resources';
export type { ResourcePoolState, CombatResourceResponse } from './resources';

export {
  adminGrantTurns,
  adminSetLevel,
  adminGrantXp,
  adminSetAttributes,
  adminGetItemTemplates,
  adminGrantItem,
  adminGetEventTemplates,
  adminGetActiveEvents,
  adminSpawnEvent,
  adminCancelEvent,
  adminGetMobs,
  adminGetMobFamilies,
  adminSpawnBoss,
  adminGetZones,
  adminDiscoverAllZones,
  adminTeleport,
  adminSpawnEncounter,
  adminGetResourceNodes,
  adminSpawnResourceNode,
} from './admin';
export type {
  AdminItemTemplate,
  AdminZone,
  AdminMobTemplate,
  AdminMobFamily,
  AdminEventTemplate,
  AdminActiveEvent,
  AdminResourceNode,
} from './admin';

export {
  getTemplates,
  getActiveTemplate,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  activateTemplate,
} from './templates';
export type { TemplateAction, TemplateResponse } from './templates';

export {
  getPlayerGuild,
  createGuild,
  searchGuilds,
  joinGuild,
  leaveGuild,
  kickGuildMember,
  promoteGuildMember,
  demoteGuildMember,
  transferGuildLeadership,
  disbandGuild,
  updateGuildSettings,
  getGuildLog,
  getGuildUpgrades,
  activateGuildUpgrade,
  getGuildContracts,
  getGuildProjects,
  startGuildProject,
  contributeProjectTurns,
  contributeProjectMaterials,
  getGuildSpecialization,
  selectGuildSpecialization,
  respecGuildSpecialization,
  requestJoinGuild,
  getGuildJoinRequests,
  acceptJoinRequest,
  rejectJoinRequest,
} from './guild';
export type {
  GuildResponse,
  GuildMemberResponse,
  PlayerGuildResponse,
  GuildSearchResponse,
  GuildLogResponse,
  GuildUpgradeResponse,
  GuildUpgradeTierResponse,
  GuildAvailableUpgradeResponse,
  GuildUpgradesResponse,
  GuildContractResponse,
  GuildContractsResponse,
  GuildProjectResponse,
  GuildProjectAvailableResponse,
  GuildProjectsListResponse,
  GuildProjectContributionResponse,
  SpecializationStatusResponse,
  SpecializationTierBonusResponse,
  GuildJoinRequestResponse,
  GuildJoinRequestsResponse,
} from './guild';

export { getSkillPointState, allocateSkillPoint, respecSkillPoints } from './skillPoints';
export type { SkillPointState } from './skillPoints';
