export { fetchApi, clearStoredTokens, getJwtExpMs } from './core';
export type { ApiResponse } from './core';

export { register, login, refreshToken } from './auth';

export {
  getPlayer,
  updatePlayerSettings,
  updateTutorialStep,
  getPlayerAttributes,
  allocatePlayerAttribute,
  getSkills,
  getEquipment,
  getBestiary,
  getTurns,
  spendTurns,
  getHpState,
  restEstimate,
  rest,
  recoverFromKnockout,
} from './player';
export type { PlayerSettings } from './player';

export {
  getZones,
  travelToZone,
  estimateExploration,
  startExploration,
  startCombat,
  startCombatFromEncounterSite,
  getEncounterSites,
  selectSiteStrategy,
  abandonEncounterSites,
  getCombatLog,
  getCombatLogs,
} from './combat';
export type {
  CombatLogEntryResponse,
  SkillXpGrantResponse,
  CombatOutcomeResponse,
  CombatSourceResponse,
  CombatResultResponse,
  CombatFightResult,
  CombatResponse,
  CombatHistoryListItemResponse,
  CombatHistoryResponse,
  CombatHistoryQuery,
  EncounterSitesQuery,
  EncounterSitesResponse,
} from './combat';

export {
  getInventory,
  destroyInventoryItem,
  useItem,
  repairItem,
  equip,
  unequip,
  getGatheringNodes,
  mine,
  getCraftingRecipes,
  craft,
  salvage,
  forgeUpgrade,
  forgeReroll,
} from './items';
export type {
  GatheringNodesQuery,
  GatheringNodesResponse,
} from './items';

export {
  getPvpRating,
  getPvpLadder,
  scoutPvpOpponent,
  challengePvpOpponent,
  getPvpMatchDetail,
  getPvpHistory,
  getPvpNotifications,
  getPvpNotificationCount,
  markPvpNotificationsRead,
  getChatHistory,
  getActiveEvents,
  getZoneEvents,
  getActiveBossEncounters,
  getBossEncounter,
  signUpForBoss,
  getBossHistory,
  getAchievements,
  getAchievementUnclaimedCount,
  claimAchievementReward,
  getActiveTitle,
  setActiveTitle,
  getLeaderboardCategories,
  getLeaderboard,
} from './social';
export type {
  PvpRatingResponse,
  PvpLadderEntry,
  PvpLadderResponse,
  PvpScoutData,
  PvpMatchResponse,
  PvpChallengeResponse,
  PvpMatchDetailResponse,
  PvpNotification,
  WorldEventResponse,
  BossPlayerReward,
  BossRoundSummary,
  BossEncounterResponse,
  BossParticipantResponse,
  BossHistoryEntry,
  AchievementRewardResponse,
  PlayerAchievementProgress,
  AchievementsResponse,
  LeaderboardEntry,
  LeaderboardResponse,
  LeaderboardCategoryGroup,
  LeaderboardCategoriesResponse,
} from './social';

export {
  adminGrantTurns,
  adminSetLevel,
  adminGrantXp,
  adminSetAttributes,
  adminGetItemTemplates,
  adminGrantItem,
  adminGetEventTemplates,
  adminGetActiveEvents,
  adminSpawnEvent,
  adminCancelEvent,
  adminGetMobs,
  adminGetMobFamilies,
  adminSpawnBoss,
  adminGetZones,
  adminDiscoverAllZones,
  adminTeleport,
  adminSpawnEncounter,
  adminGetResourceNodes,
  adminSpawnResourceNode,
} from './admin';
export type {
  AdminItemTemplate,
  AdminZone,
  AdminMobTemplate,
  AdminMobFamily,
  AdminEventTemplate,
  AdminActiveEvent,
  AdminResourceNode,
} from './admin';
