import type { AchievementDef } from '../types/achievement.types';

// --- Combat achievements ---
const COMBAT_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'combat_kills_100',
    category: 'combat',
    title: 'Monster Hunter',
    description: 'Kill 100 monsters',
    statKey: 'totalKills',
    threshold: 100,
  },
  {
    id: 'combat_kills_500',
    category: 'combat',
    title: 'Warrior',
    description: 'Kill 500 monsters',
    titleReward: 'The Warrior',
    statKey: 'totalKills',
    threshold: 500,
    tier: 2,
  },
  {
    id: 'combat_kills_1000',
    category: 'combat',
    title: 'Slayer',
    description: 'Kill 1,000 monsters',
    titleReward: 'The Slayer',
    statKey: 'totalKills',
    threshold: 1000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'combat_kills_5000',
    category: 'combat',
    title: 'Annihilator',
    description: 'Kill 5,000 monsters',
    titleReward: 'The Annihilator',
    statKey: 'totalKills',
    threshold: 5000,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_kills_10000',
    category: 'combat',
    title: 'Extinction Event',
    description: 'Kill 10,000 monsters',
    titleReward: 'Extinction Event',
    statKey: 'totalKills',
    threshold: 10000,
    tier: 5,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
  {
    id: 'combat_boss_1',
    category: 'combat',
    title: 'Boss Hunter',
    description: 'Defeat 1 boss',
    statKey: 'totalBossKills',
    threshold: 1,
  },
  {
    id: 'combat_boss_10',
    category: 'combat',
    title: 'Boss Crusher',
    description: 'Defeat 10 bosses',
    titleReward: 'Bane of Bosses',
    statKey: 'totalBossKills',
    threshold: 10,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'combat_boss_25',
    category: 'combat',
    title: 'Raid Leader',
    description: 'Defeat 25 bosses',
    titleReward: 'Raid Leader',
    statKey: 'totalBossKills',
    threshold: 25,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_pvp_1',
    category: 'combat',
    title: 'Gladiator',
    description: 'Win 1 PvP match',
    statKey: 'totalPvpWins',
    threshold: 1,
  },
  {
    id: 'combat_pvp_25',
    category: 'combat',
    title: 'Pit Fighter',
    description: 'Win 25 PvP matches',
    titleReward: 'Pit Fighter',
    statKey: 'totalPvpWins',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'combat_pvp_100',
    category: 'combat',
    title: 'Arena Champion',
    description: 'Win 100 PvP matches',
    titleReward: 'Champion',
    statKey: 'totalPvpWins',
    threshold: 100,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_streak_5',
    category: 'combat',
    title: 'On A Roll',
    description: 'Achieve a 5 PvP win streak',
    statKey: 'bestPvpWinStreak',
    threshold: 5,
  },
  {
    id: 'combat_streak_10',
    category: 'combat',
    title: 'Unstoppable',
    description: 'Achieve a 10 PvP win streak',
    titleReward: 'The Unstoppable',
    statKey: 'bestPvpWinStreak',
    threshold: 10,
    tier: 2,
    secret: true,
  },
];

// --- Exploration achievements ---
const EXPLORATION_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'explore_zones_3',
    category: 'exploration',
    title: 'Wanderer',
    description: 'Discover 3 zones',
    statKey: 'totalZonesDiscovered',
    threshold: 3,
    rewards: [{ type: 'turns', amount: 1000 }],
  },
  {
    id: 'explore_zones_5',
    category: 'exploration',
    title: 'Pathfinder',
    description: 'Discover 5 zones',
    titleReward: 'The Pathfinder',
    statKey: 'totalZonesDiscovered',
    threshold: 5,
    tier: 2,
  },
  {
    id: 'explore_zones_all',
    category: 'exploration',
    title: 'Cartographer',
    description: 'Discover all zones',
    titleReward: 'The Cartographer',
    statKey: 'totalZonesDiscovered',
    threshold: 11,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'explore_full_1',
    category: 'exploration',
    title: 'Thorough',
    description: 'Fully explore 1 zone',
    statKey: 'totalZonesFullyExplored',
    threshold: 1,
  },
  {
    id: 'explore_full_3',
    category: 'exploration',
    title: 'Surveyor',
    description: 'Fully explore 3 zones',
    titleReward: 'The Surveyor',
    statKey: 'totalZonesFullyExplored',
    threshold: 3,
    tier: 2,
  },
  {
    id: 'explore_full_all',
    category: 'exploration',
    title: 'World Walker',
    description: 'Fully explore all zones',
    titleReward: 'World Walker',
    statKey: 'totalZonesFullyExplored',
    threshold: 9,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- Crafting achievements ---
const CRAFTING_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'craft_total_1',
    category: 'crafting',
    title: 'Apprentice',
    description: 'Craft 1 item',
    statKey: 'totalCrafts',
    threshold: 1,
  },
  {
    id: 'craft_total_50',
    category: 'crafting',
    title: 'Artisan',
    description: 'Craft 50 items',
    titleReward: 'The Artisan',
    statKey: 'totalCrafts',
    threshold: 50,
    tier: 2,
  },
  {
    id: 'craft_total_500',
    category: 'crafting',
    title: 'Master Crafter',
    description: 'Craft 500 items',
    titleReward: 'Master Crafter',
    statKey: 'totalCrafts',
    threshold: 500,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'craft_rare_1',
    category: 'crafting',
    title: 'Lucky Break',
    description: 'Craft a rare item',
    statKey: 'totalRaresCrafted',
    threshold: 1,
  },
  {
    id: 'craft_epic_1',
    category: 'crafting',
    title: 'Epic Forger',
    description: 'Craft an epic item',
    titleReward: 'The Forger',
    statKey: 'totalEpicsCrafted',
    threshold: 1,
    tier: 3,
  },
  {
    id: 'craft_legendary_1',
    category: 'crafting',
    title: 'Legendary Smith',
    description: 'Craft a legendary item',
    titleReward: 'Legendsmith',
    statKey: 'totalLegendariesCrafted',
    threshold: 1,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'craft_salvage_50',
    category: 'crafting',
    title: 'Scrapper',
    description: 'Salvage 50 items',
    statKey: 'totalSalvages',
    threshold: 50,
  },
  {
    id: 'craft_salvage_500',
    category: 'crafting',
    title: 'Recycler',
    description: 'Salvage 500 items',
    titleReward: 'The Recycler',
    statKey: 'totalSalvages',
    threshold: 500,
    tier: 2,
  },
  {
    id: 'craft_forge_25',
    category: 'crafting',
    title: 'Tinkerer',
    description: 'Forge upgrade 25 times',
    statKey: 'totalForgeUpgrades',
    threshold: 25,
  },
];

// --- Skills achievements ---
const SKILLS_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'skill_any_10',
    category: 'skills',
    title: 'Dedicated',
    description: 'Reach level 10 in any skill',
    statKey: 'highestSkillLevel',
    threshold: 10,
  },
  {
    id: 'skill_any_25',
    category: 'skills',
    title: 'Specialist',
    description: 'Reach level 25 in any skill',
    titleReward: 'The Specialist',
    statKey: 'highestSkillLevel',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'skill_any_50',
    category: 'skills',
    title: 'Master',
    description: 'Reach level 50 in any skill',
    titleReward: 'The Master',
    statKey: 'highestSkillLevel',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'level_10',
    category: 'skills',
    title: 'Rising Star',
    description: 'Reach character level 10',
    statKey: 'highestCharacterLevel',
    threshold: 10,
  },
  {
    id: 'level_25',
    category: 'skills',
    title: 'Veteran',
    description: 'Reach character level 25',
    titleReward: 'Veteran',
    statKey: 'highestCharacterLevel',
    threshold: 25,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'level_50',
    category: 'skills',
    title: 'Legend',
    description: 'Reach character level 50',
    titleReward: 'The Legend',
    statKey: 'highestCharacterLevel',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- Gathering achievements ---
const GATHERING_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'gather_total_10',
    category: 'gathering',
    title: 'Prospector',
    description: 'Gather 10 times',
    statKey: 'totalGatheringActions',
    threshold: 10,
  },
  {
    id: 'gather_total_100',
    category: 'gathering',
    title: 'Harvester',
    description: 'Gather 100 times',
    statKey: 'totalGatheringActions',
    threshold: 100,
    tier: 2,
  },
  {
    id: 'gather_total_500',
    category: 'gathering',
    title: 'Resource Baron',
    description: 'Gather 500 times',
    titleReward: 'The Harvester',
    statKey: 'totalGatheringActions',
    threshold: 500,
    tier: 3,
  },
  {
    id: 'gather_total_1000',
    category: 'gathering',
    title: 'Strip Miner',
    description: 'Gather 1,000 times',
    titleReward: 'Strip Miner',
    statKey: 'totalGatheringActions',
    threshold: 1000,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
];

// --- Bestiary achievements ---
const BESTIARY_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'bestiary_unique_10',
    category: 'bestiary',
    title: 'Naturalist',
    description: 'Encounter 10 unique monsters',
    statKey: 'totalUniqueMonsterKills',
    threshold: 10,
  },
  {
    id: 'bestiary_unique_25',
    category: 'bestiary',
    title: 'Monster Scholar',
    description: 'Encounter 25 unique monsters',
    titleReward: 'The Scholar',
    statKey: 'totalUniqueMonsterKills',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'bestiary_complete_1',
    category: 'bestiary',
    title: 'Completionist',
    description: 'Master all prefixes for 1 mob',
    statKey: 'totalBestiaryCompleted',
    threshold: 1,
  },
  {
    id: 'bestiary_complete_5',
    category: 'bestiary',
    title: 'Zoologist',
    description: 'Master 5 mob bestiary entries',
    titleReward: 'The Zoologist',
    statKey: 'totalBestiaryCompleted',
    threshold: 5,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'bestiary_complete_all',
    category: 'bestiary',
    title: 'Encyclopedist',
    description: 'Master all mob bestiary entries',
    titleReward: 'The Encyclopedist',
    statKey: 'totalBestiaryCompleted',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- General achievements ---
const GENERAL_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'turns_10000',
    category: 'general',
    title: 'Time Invested',
    description: 'Spend 10,000 turns',
    statKey: 'totalTurnsSpent',
    threshold: 10000,
  },
  {
    id: 'turns_100000',
    category: 'general',
    title: 'Dedicated Adventurer',
    description: 'Spend 100,000 turns',
    titleReward: 'The Dedicated',
    statKey: 'totalTurnsSpent',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'turns_1000000',
    category: 'general',
    title: 'No-Lifer',
    description: 'Spend 1,000,000 turns',
    titleReward: 'The No-Lifer',
    statKey: 'totalTurnsSpent',
    threshold: 1000000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'recipe_10',
    category: 'general',
    title: 'Cookbook',
    description: 'Learn 10 recipes',
    statKey: 'totalRecipesLearned',
    threshold: 10,
  },
  {
    id: 'recipe_25',
    category: 'general',
    title: 'Recipe Collector',
    description: 'Learn 25 recipes',
    titleReward: 'The Collector',
    statKey: 'totalRecipesLearned',
    threshold: 25,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  // Secret achievements
  {
    id: 'secret_first_death',
    category: 'general',
    title: 'Humbling Experience',
    description: 'Get knocked out for the first time',
    statKey: 'totalDeaths',
    threshold: 1,
    secret: true,
  },
  {
    id: 'tutorial_complete',
    category: 'general',
    title: 'The Graduate',
    description: 'Complete the tutorial',
    titleReward: 'The Graduate',
    statKey: 'tutorialCompleted',
    threshold: 1,
  },
  {
    id: 'secret_legendary_crit',
    category: 'crafting',
    title: 'Golden Hands',
    description: 'Craft a legendary item through a critical success',
    titleReward: 'Golden Hands',
    statKey: 'totalLegendariesCrafted',
    threshold: 1,
    tier: 5,
    secret: true,
  },
];

// --- Family achievements (generated for all 19 families) ---
const FAMILY_KEYS = [
  'vermin', 'spiders', 'boars', 'wolves', 'bandits',
  'treants', 'spirits', 'fae', 'bats', 'goblins',
  'golems', 'crawlers', 'harpies', 'undead', 'swampBeasts',
  'witches', 'elementals', 'serpents', 'abominations',
] as const;

const FAMILY_DISPLAY_NAMES: Record<string, string> = {
  vermin: 'Vermin',
  spiders: 'Spider',
  boars: 'Boar',
  wolves: 'Wolf',
  bandits: 'Bandit',
  treants: 'Treant',
  spirits: 'Spirit',
  fae: 'Fae',
  bats: 'Bat',
  goblins: 'Goblin',
  golems: 'Golem',
  crawlers: 'Crawler',
  harpies: 'Harpy',
  undead: 'Undead',
  swampBeasts: 'Swamp Beast',
  witches: 'Witch',
  elementals: 'Elemental',
  serpents: 'Serpent',
  abominations: 'Abomination',
};

// Maps family key to the unique item template ID awarded at 1,000 kills
export const FAMILY_REWARD_ITEMS: Record<string, string> = {
  vermin: 'achievement_vermin_gloves',
  spiders: 'achievement_spiders_boots',
  boars: 'achievement_boars_chest',
  wolves: 'achievement_wolves_chest',
  bandits: 'achievement_bandits_weapon',
  treants: 'achievement_treants_shield',
  spirits: 'achievement_spirits_charm',
  fae: 'achievement_fae_ring',
  bats: 'achievement_bats_helm',
  goblins: 'achievement_goblins_helm',
  golems: 'achievement_golems_charm',
  crawlers: 'achievement_crawlers_legs',
  harpies: 'achievement_harpies_boots',
  undead: 'achievement_undead_gloves',
  swampBeasts: 'achievement_swampBeasts_belt',
  witches: 'achievement_witches_helm',
  elementals: 'achievement_elementals_neck',
  serpents: 'achievement_serpents_ring',
  abominations: 'achievement_abominations_chest',
};

const FAMILY_ACHIEVEMENTS: AchievementDef[] = FAMILY_KEYS.flatMap((key) => {
  const name = FAMILY_DISPLAY_NAMES[key];
  return [
    {
      id: `family_${key}_500`,
      category: 'family' as const,
      title: `${name} Hunter`,
      description: `Kill 500 ${name}s`,
      familyKey: key,
      threshold: 500,
      tier: 1,
    },
    {
      id: `family_${key}_2500`,
      category: 'family' as const,
      title: `${name} Slayer`,
      description: `Kill 2,500 ${name}s`,
      titleReward: `${name} Slayer`,
      familyKey: key,
      threshold: 2500,
      tier: 2,
    },
    {
      id: `family_${key}_5000`,
      category: 'family' as const,
      title: `${name}'s Bane`,
      description: `Kill 5,000 ${name}s`,
      titleReward: `${name}'s Bane`,
      familyKey: key,
      threshold: 5000,
      tier: 3,
      rewards: [{ type: 'item', amount: 1, itemTemplateId: FAMILY_REWARD_ITEMS[key] }],
    },
  ];
});

export const ALL_ACHIEVEMENTS: AchievementDef[] = [
  ...COMBAT_ACHIEVEMENTS,
  ...EXPLORATION_ACHIEVEMENTS,
  ...CRAFTING_ACHIEVEMENTS,
  ...SKILLS_ACHIEVEMENTS,
  ...GATHERING_ACHIEVEMENTS,
  ...BESTIARY_ACHIEVEMENTS,
  ...GENERAL_ACHIEVEMENTS,
  ...FAMILY_ACHIEVEMENTS,
];

// Lookup maps for efficient access
export const ACHIEVEMENTS_BY_ID = new Map(ALL_ACHIEVEMENTS.map((a) => [a.id, a]));
export const ACHIEVEMENTS_BY_STAT_KEY = new Map<string, AchievementDef[]>();
export const ACHIEVEMENTS_BY_FAMILY_KEY = new Map<string, AchievementDef[]>();

for (const a of ALL_ACHIEVEMENTS) {
  if (a.statKey) {
    const list = ACHIEVEMENTS_BY_STAT_KEY.get(a.statKey) ?? [];
    list.push(a);
    ACHIEVEMENTS_BY_STAT_KEY.set(a.statKey, list);
  }
  if (a.familyKey) {
    const list = ACHIEVEMENTS_BY_FAMILY_KEY.get(a.familyKey) ?? [];
    list.push(a);
    ACHIEVEMENTS_BY_FAMILY_KEY.set(a.familyKey, list);
  }
}
