import { PREMIUM_CONSTANTS } from './gameConstants';
import type { AchievementDef } from '../types/achievement.types';

// --- Combat achievements ---
const COMBAT_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'combat_kills_100',
    category: 'combat',
    title: 'Monster Hunter',
    description: 'A hundred down. The Pocketrealm has noticed you, and it is not impressed. Keep going.',
    flavorText: 'One hundred creatures have fallen to your hand. The Forest Edge knows your name now, or at least your smell. Either way, they\'ve stopped underestimating you.',
    statKey: 'totalKills',
    threshold: 100,
  },
  {
    id: 'combat_kills_500',
    category: 'combat',
    title: 'Warrior',
    description: 'You fight because you can, not because you must. The title is earned, not given.',
    flavorText: 'Five hundred. What started as survival has become something closer to a profession. The blood washes out of most fabrics now, and you have stopped flinching at the sound of your own sword.',
    titleReward: 'The Warrior',
    statKey: 'totalKills',
    threshold: 500,
    tier: 2,
  },
  {
    id: 'combat_kills_1000',
    category: 'combat',
    title: 'Slayer',
    description: 'One thousand. The monsters have started telling stories about you. None of them end well.',
    flavorText: 'A thousand lives ended by your hand. Tavern songs don\'t capture the reality of it: the repetition, the sore arms, the sheer volume of rat pelts. But here you are, still standing, still swinging.',
    titleReward: 'The Slayer',
    statKey: 'totalKills',
    threshold: 1000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'combat_kills_5000',
    category: 'combat',
    title: 'Annihilator',
    description: 'You are no longer part of the food chain. You are the reason it has gaps.',
    flavorText: 'Five thousand. Entire species have revised their migration patterns to avoid you. Scholars at Millbrook have begun tracking your impact on local ecosystems, and the early findings are, in their words, \'concerning.\'',
    titleReward: 'The Annihilator',
    statKey: 'totalKills',
    threshold: 5000,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_kills_10000',
    category: 'combat',
    title: 'Extinction Event',
    description: 'Congratulations. Future generations of monsters will use your name to frighten their young. Assuming there are future generations.',
    flavorText: 'Ten thousand. The number is difficult to hold in your mind, so don\'t try. Just know that somewhere, a very tired clerk is running out of space in the casualty ledger, and the Pocketrealm\'s bestiary has started listing you as a natural disaster.',
    titleReward: 'Extinction Event',
    statKey: 'totalKills',
    threshold: 10000,
    tier: 5,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
  {
    id: 'combat_boss_1',
    category: 'combat',
    title: 'Boss Hunter',
    description: 'You looked something terrible in the eye and it blinked first. Welcome to the deep end.',
    flavorText: 'Your first boss. The ground shook, the air tasted like copper, and for one clarifying moment you understood exactly how small you are. Then you won anyway. That is the part that matters.',
    statKey: 'totalBossKills',
    threshold: 1,
  },
  {
    id: 'combat_boss_10',
    category: 'combat',
    title: 'Boss Crusher',
    description: 'Ten of the Pocketrealm\'s worst, brought low. When lesser creatures see you coming, they have started stepping aside. Wise of them.',
    flavorText: 'Ten bosses felled. You have developed a routine for this: scout, prepare, engage, survive. The preparation takes longer than the killing now, which says more about you than any title could. The creatures that rule the wild places have started to recognize you, and recognition is the first step toward fear.',
    titleReward: 'Bane of Bosses',
    statKey: 'totalBossKills',
    threshold: 10,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'combat_boss_25',
    category: 'combat',
    title: 'Raid Leader',
    description: 'Others follow where you lead, because you have already been everywhere worth going and killed everything worth killing. The title is a formality. The reputation came first.',
    flavorText: 'Twenty-five. You have fought the Alpha Wolf in its den and the Ancient Spirit in its sanctum. You have stood in places where the world bends under the weight of old, furious things, and you walked out carrying their trophies. The Pocketrealm does not hand out legends. You carved this one yourself, encounter by encounter, each one a story that nobody who wasn\'t there would believe.',
    titleReward: 'Raid Leader',
    statKey: 'totalBossKills',
    threshold: 25,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_pvp_1',
    category: 'combat',
    title: 'Gladiator',
    description: 'Your first victory over a fellow adventurer. The arena remembers, even if they would rather not.',
    flavorText: 'Monsters fight because they must. You fought another adventurer because you chose to. That is a different kind of violence entirely, and the fact that you won says something about you. Whether it says something good is a question for quieter moments.',
    statKey: 'totalPvpWins',
    threshold: 1,
  },
  {
    id: 'combat_pvp_25',
    category: 'combat',
    title: 'Pit Fighter',
    description: 'You do not fight in the arena to prove a point. You fight because you are good at it, and being good at things is its own reward.',
    flavorText: 'Twenty-five opponents faced, twenty-five lessons delivered. You have learned to read a fighter\'s intentions in the way they shift their weight, the half-second pause before a spell, the telltale grip change that says \'I am about to do something desperate.\' You read all of it. And then you hit them anyway.',
    titleReward: 'Pit Fighter',
    statKey: 'totalPvpWins',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'combat_pvp_100',
    category: 'combat',
    title: 'Arena Champion',
    description: 'Champion. Not because someone gave you a crown, but because a hundred people tried to take it and failed.',
    flavorText: 'One hundred victories. The arena has become a second home, which says something unfortunate about your social life but something extraordinary about your combat instincts. Opponents study your patterns. They prepare strategies. They discuss your tendencies over drinks at The Crooked Antler. And then they lose to you anyway, because knowing what you do and stopping you from doing it are entirely separate problems.',
    titleReward: 'Champion',
    statKey: 'totalPvpWins',
    threshold: 100,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'combat_streak_5',
    category: 'combat',
    title: 'On A Roll',
    description: 'Five consecutive victories. You are not just winning; you are making it look deliberate.',
    flavorText: 'Five in a row. Luck gets you two, maybe three. After that, it is just you: reading faster, hitting cleaner, making fewer of the mistakes that separate a fighter from a spectacle.',
    statKey: 'bestPvpWinStreak',
    threshold: 5,
  },
  {
    id: 'combat_streak_10',
    category: 'combat',
    title: 'Unstoppable',
    description: 'Ten in a row. They stopped trying to beat you and started trying to survive. There is a difference, and you taught it to them.',
    flavorText: 'Ten. Consecutive. Victories. The arena crowd has gone from cheering to something closer to awe, the kind of respectful silence usually reserved for natural disasters and very large predators. Nobody has a plan for you anymore. They have hopes, and wishes, and the vague optimism of someone who buys a lottery ticket. But plans? Those stopped working five fights ago.',
    titleReward: 'The Unstoppable',
    statKey: 'bestPvpWinStreak',
    threshold: 10,
    tier: 2,
    secret: true,
  },
];

// --- Exploration achievements ---
const EXPLORATION_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'explore_zones_3',
    category: 'exploration',
    title: 'Wanderer',
    description: 'You have seen enough to know there is more. The world just got wider, and it is not done yet.',
    flavorText: 'Three zones. The Forest Edge, and then two more places that the Forest Edge did not prepare you for. The Pocketrealm is larger than it looked from Millbrook\'s gate, and every new horizon makes the last one feel smaller.',
    statKey: 'totalZonesDiscovered',
    threshold: 3,
    rewards: [{ type: 'turns', amount: 1000 }],
  },
  {
    id: 'explore_zones_5',
    category: 'exploration',
    title: 'Pathfinder',
    description: 'Half the world is open to you. The other half is waiting to see if you are serious.',
    flavorText: 'Five zones mapped in your mind, five sets of dangers catalogued, five places where the locals have learned your footsteps. The paths between them are becoming familiar, which is the Pocketrealm\'s way of telling you it is time to find harder ones.',
    titleReward: 'The Pathfinder',
    statKey: 'totalZonesDiscovered',
    threshold: 5,
    tier: 2,
  },
  {
    id: 'explore_zones_all',
    category: 'exploration',
    title: 'Cartographer',
    description: 'You have seen it all. Every forest, every cave, every ruin. The map is complete. What you do with it is your business.',
    flavorText: 'Every zone, from the sunlit farms beyond Millbrook to the drowned corridors of the Sunken Ruins. You have stood in places that most adventurers only hear about in Maren\'s tavern, and you walked there on your own feet. The Pocketrealm has no more secrets of geography to offer you. Only the secrets that live inside them.',
    titleReward: 'The Cartographer',
    statKey: 'totalZonesDiscovered',
    threshold: 11,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'explore_full_1',
    category: 'exploration',
    title: 'Thorough',
    description: 'You do not leave loose ends. One zone has given up all its secrets to you.',
    flavorText: 'One zone, turned inside out. Every path walked, every corner checked, every tier uncovered. Most adventurers pass through. You stayed until there was nothing left to find, which takes a particular kind of stubbornness that the Pocketrealm respects.',
    statKey: 'totalZonesFullyExplored',
    threshold: 1,
  },
  {
    id: 'explore_full_3',
    category: 'exploration',
    title: 'Surveyor',
    description: 'Three zones, fully mapped, fully understood. The wilderness bends around your knowledge of it.',
    flavorText: 'Three zones stripped bare. You know where the copper veins run thin, where the wolves change patrol routes, and which goblin tunnels loop back on themselves. You have moved past exploration and into something closer to ownership.',
    titleReward: 'The Surveyor',
    statKey: 'totalZonesFullyExplored',
    threshold: 3,
    tier: 2,
  },
  {
    id: 'explore_full_all',
    category: 'exploration',
    title: 'World Walker',
    description: 'There is not a single square foot of wilderness you have not claimed with your presence. The world is mapped. You are the World Walker.',
    flavorText: 'Nine wild zones. Every exploration tier reached, every hidden corner illuminated, every ambient threat accounted for. You have walked from the gentle oaks of the Forest Edge to the abyssal dark of the Sunken Ruins and left nothing undiscovered behind you. The Pocketrealm has been measured, and the one holding the ruler is you.',
    titleReward: 'World Walker',
    statKey: 'totalZonesFullyExplored',
    threshold: 9,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- Crafting achievements ---
const CRAFTING_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'craft_total_1',
    category: 'crafting',
    title: 'Apprentice',
    description: 'You made a thing. It did not explode. This is how every great smith, alchemist, and cook in history started.',
    flavorText: 'Your first creation. It is not perfect. Kessa would call it \'functional,\' which from her is practically a standing ovation. But it is yours, made by your hands from materials you gathered, and it exists because you decided it should. That counts for something.',
    statKey: 'totalCrafts',
    threshold: 1,
  },
  {
    id: 'craft_total_50',
    category: 'crafting',
    title: 'Artisan',
    description: 'Fifty crafted, each one better than the last. Or at least different from the last. Growth takes many forms.',
    flavorText: 'Fifty items. Your hands have learned the rhythms of the forge, the bench, and the tanning rack without your mind needing to instruct them. You no longer burn yourself on hot ingots (usually), and the quality of your work has moved from \'surprising\' to \'expected.\' In the Crafting Quarter, that is the highest compliment.',
    titleReward: 'The Artisan',
    statKey: 'totalCrafts',
    threshold: 50,
    tier: 2,
  },
  {
    id: 'craft_total_500',
    category: 'crafting',
    title: 'Master Crafter',
    description: 'Five hundred items forged, stitched, brewed, and shaped. The materials know your hands. The craft knows your name.',
    flavorText: 'Five hundred. The raw materials of the Pocketrealm have passed through your hands so many times that you can identify ore by weight, wood by smell, and leather by the way it resists the needle. Kessa Ironweld has stopped checking your work. Vesper Tain has started asking for your opinion on compound stability. You have not merely learned a trade; you have become the standard against which the trade is measured.',
    titleReward: 'Master Crafter',
    statKey: 'totalCrafts',
    threshold: 500,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'craft_rare_1',
    category: 'crafting',
    title: 'Lucky Break',
    description: 'Your first rare craft. Luck or skill? Probably luck. But do not let that stop you from taking full credit.',
    flavorText: 'The hammer fell, the metal sang, and something clicked into place that had no business clicking. A rare item, born from the same materials as a dozen common ones before it, distinguished by nothing except the inexplicable alchemy of the right force at the right angle at the right moment. Vesper would call it chemistry. Kessa would call it instinct. You are not sure what to call it, but you would like it to happen again.',
    statKey: 'totalRaresCrafted',
    threshold: 1,
  },
  {
    id: 'craft_epic_1',
    category: 'crafting',
    title: 'Epic Forger',
    description: 'You have forged something that transcends the ordinary. The purple glow is not decoration. It is a promise.',
    flavorText: 'Epic. The word gets thrown around too freely in tavern stories, but not here. What you made is genuinely, objectively exceptional: a piece of equipment that will outlast its owner, outperform its peers, and make Kessa Ironweld give it a long, silent look that might be jealousy and might be respect. She will not tell you which.',
    titleReward: 'The Forger',
    statKey: 'totalEpicsCrafted',
    threshold: 1,
    tier: 3,
  },
  {
    id: 'craft_legendary_1',
    category: 'crafting',
    title: 'Legendary Smith',
    description: 'Legendary. Not found in a ruin or stripped from a fallen god. Made. By you. At a workbench. Sometimes the extraordinary begins with ordinary hands.',
    flavorText: 'There it is. A legendary item, crafted by mortal hands from mortal materials, yet somehow more than the sum of its parts. The grain of the metal catches light that is not there. The edge holds despite all physical reason. Aldric Voss will want to log it. Maren Ashwick will want to display it above the bar. Kessa Ironweld will say nothing at all, which is how you will know that what you have made is real.',
    titleReward: 'Legendsmith',
    statKey: 'totalLegendariesCrafted',
    threshold: 1,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'craft_salvage_50',
    category: 'crafting',
    title: 'Scrapper',
    description: 'Salvage 50 items',
    statKey: 'totalSalvages',
    threshold: 50,
  },
  {
    id: 'craft_salvage_500',
    category: 'crafting',
    title: 'Recycler',
    description: 'Salvage 500 items',
    titleReward: 'The Recycler',
    statKey: 'totalSalvages',
    threshold: 500,
    tier: 2,
  },
  {
    id: 'craft_forge_25',
    category: 'crafting',
    title: 'Tinkerer',
    description: 'Forge upgrade 25 times',
    statKey: 'totalForgeUpgrades',
    threshold: 25,
  },
];

// --- Skills achievements ---
const SKILLS_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'skill_any_10',
    category: 'skills',
    title: 'Dedicated',
    description: 'Level 10. You have stopped being a beginner and started being dangerous. The skill knows your name now.',
    flavorText: 'Ten levels in a single discipline. What began as fumbling has become competence, and competence, in the Pocketrealm, is the difference between coming home and not coming home. Rowan Delk would nod at this. Kessa Ironweld might too, though she would pretend she didn\'t.',
    statKey: 'highestSkillLevel',
    threshold: 10,
  },
  {
    id: 'skill_any_25',
    category: 'skills',
    title: 'Specialist',
    description: 'Level 25. You are no longer learning a skill. You are becoming it.',
    flavorText: 'Twenty-five levels of deliberate, focused practice. You have chosen your path and walked it past the point where most people turn back, through the plateau where progress feels impossible and out the other side into territory that belongs to the committed. Your hands do things your mind has not yet named. Your instincts have outpaced your understanding, which is exactly how mastery begins.',
    titleReward: 'The Specialist',
    statKey: 'highestSkillLevel',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'skill_any_50',
    category: 'skills',
    title: 'Master',
    description: 'Level 50. Mastery. The word used to feel aspirational. Now it fits like a glove you have worn thin from use.',
    flavorText: 'Fifty. The number does not do it justice. Fifty levels is ten thousand repetitions, a hundred failed experiments, and one long, quiet conversation with a discipline that has decided to let you in on its secrets. Vesper Tain reached it with alchemy and said the world looked different afterwards, as if she had been reading everything through a dirty window until the day it came clean. Whether you reached fifty with a blade, a pickaxe, or a spell, the feeling is the same: you are no longer practicing. You are fluent.',
    titleReward: 'The Master',
    statKey: 'highestSkillLevel',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'level_10',
    category: 'skills',
    title: 'Rising Star',
    description: 'Character level 10. You have outgrown the starting gear and started earning the attention of things that do not eat rats.',
    flavorText: 'Level 10. The Pocketrealm\'s way of confirming that you are, in fact, not going away. Your skills have broadened, your stats have grown, and the creatures near Millbrook have revised their opinions about you. The forest rats no longer bother. The wolves are still deciding.',
    statKey: 'highestCharacterLevel',
    threshold: 10,
  },
  {
    id: 'level_25',
    category: 'skills',
    title: 'Veteran',
    description: 'Level 25. The Pocketrealm has stopped testing you and started relying on you. That is either an honour or a warning.',
    flavorText: 'Twenty-five levels of accumulated experience, worn like armour and visible in the way you move. New adventurers ask you for advice at The Crooked Antler. Maren serves your drink before you sit down. Aldric Voss files your quest completions without checking the details, because your numbers always add up. You have become a fixture, and fixtures in the Pocketrealm tend to last.',
    titleReward: 'Veteran',
    statKey: 'highestCharacterLevel',
    threshold: 25,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'level_50',
    category: 'skills',
    title: 'Legend',
    description: 'Level 50. Legend. The title is not given. It is what remains after everything else has been tested, broken, rebuilt, and proven.',
    flavorText: 'Fifty. You have stood in every zone, faced every family of creature, and survived the kind of encounters that Maren tells stories about to adventurers who have not yet left Millbrook. The number is a milestone, but the title is the truth: you are a legend, not because someone declared it, but because the Pocketrealm ran out of things to throw at you and you are still standing. Bram adds your name to the good customer list. Kessa nods when you walk past the forge. Rowan Delk, for the first time anyone can remember, looks impressed.',
    titleReward: 'The Legend',
    statKey: 'highestCharacterLevel',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- Gathering achievements ---
const GATHERING_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'gather_total_10',
    category: 'gathering',
    title: 'Prospector',
    description: 'Ten gathers. Your hands are learning what your eyes cannot teach them. This is how it begins.',
    flavorText: 'Ten swings, ten harvests, ten small conversations with the ground. You have copper dust under your nails, sap on your sleeves, and herb stains on your fingers. Rowan Delk would say this is what \'starting\' looks like. He would be right.',
    statKey: 'totalGatheringActions',
    threshold: 10,
  },
  {
    id: 'gather_total_100',
    category: 'gathering',
    title: 'Harvester',
    description: 'One hundred gathers. The land knows the sound of your tools. You are no longer a visitor; you are a regular.',
    flavorText: 'A hundred times you have knelt in the dirt, struck stone, or stripped bark, and a hundred times the Pocketrealm has given you something in return. The work is repetitive. The work is unglamorous. The work is also the reason Millbrook has ingots, planks, and potions, which makes it more important than any single fight you have ever won.',
    statKey: 'totalGatheringActions',
    threshold: 100,
    tier: 2,
  },
  {
    id: 'gather_total_500',
    category: 'gathering',
    title: 'Resource Baron',
    description: 'Five hundred times you asked the land for something, and five hundred times it answered. The title is earned through patience, not glory. That makes it rarer.',
    flavorText: 'Five hundred. The copper hollows know the shape of your pick. The oaks lean away when you approach (though that might be the treants). The herb patches recognize your step and have, Vesper suspects, begun growing slightly faster in your favourite spots, which is either a compliment or a bribe.',
    titleReward: 'The Harvester',
    statKey: 'totalGatheringActions',
    threshold: 500,
    tier: 3,
  },
  {
    id: 'gather_total_1000',
    category: 'gathering',
    title: 'Strip Miner',
    description: 'A thousand gathers. The Pocketrealm\'s economy rests on your shoulders, your calluses, and your willingness to hit one more rock. Strip Miner is not a title. It is a job description, and you have earned it.',
    flavorText: 'One thousand. The number is staggering when you say it aloud, and entirely reasonable when you consider how many ingots, planks, and potions the Pocketrealm consumes in a single week. You are the supply chain. You are the reason Kessa\'s forge stays lit, Vesper\'s bench stays stocked, and Bram\'s shelves stay full. Without combat, the Pocketrealm would be dangerous. Without gathering, it would be empty.',
    titleReward: 'Strip Miner',
    statKey: 'totalGatheringActions',
    threshold: 1000,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
];

// --- Bestiary achievements ---
const BESTIARY_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'bestiary_unique_10',
    category: 'bestiary',
    title: 'Naturalist',
    description: 'Ten unique creatures studied. The bestiary is filling in, and the patterns are starting to make a terrible kind of sense.',
    flavorText: 'Ten species catalogued: their habits observed, their weaknesses noted, their tendency to bite recorded in careful detail. You have begun to see the Pocketrealm not as a series of threats but as an ecosystem, one where everything has a role and most of those roles involve trying to eat you.',
    statKey: 'totalUniqueMonsterKills',
    threshold: 10,
  },
  {
    id: 'bestiary_unique_25',
    category: 'bestiary',
    title: 'Monster Scholar',
    description: 'Twenty-five. You know the Pocketrealm\'s creatures by name, by habit, and by the specific sound they make when they realize you are not afraid of them anymore.',
    flavorText: 'Twenty-five species. You can identify a Dire Wolf by its gait, a Goblin Warrior by its armour\'s rattle, and a Venomous Spider by the split second of silence before the bite. Vesper Tain has started citing your field notes in her research. Aldric Voss has started filing them. You are becoming, against all probability, an academic.',
    titleReward: 'The Scholar',
    statKey: 'totalUniqueMonsterKills',
    threshold: 25,
    tier: 2,
  },
  {
    id: 'bestiary_complete_1',
    category: 'bestiary',
    title: 'Completionist',
    description: 'One mob, fully mastered. You know it in your bones. Every prefix, every variant, every trick. It cannot surprise you anymore.',
    flavorText: 'One creature, studied completely. Every variant encountered, every prefix catalogued, every behaviour pattern documented. You have looked at this thing from every possible angle, and you now understand it better than it understands itself. There is a word for that kind of knowledge. The word is \'dangerous.\'',
    statKey: 'totalBestiaryCompleted',
    threshold: 1,
  },
  {
    id: 'bestiary_complete_5',
    category: 'bestiary',
    title: 'Zoologist',
    description: 'Five creatures, inside and out. The bestiary is becoming less of a field guide and more of a personal history, written in encounters and paid for in bruises.',
    flavorText: 'Five species mastered in their entirety. Your bestiary entries read like autopsy reports written by someone who genuinely enjoys their work. Rowan Delk says you look at creatures the way he looks at ore veins: with assessment, not fear. He means it as a compliment. It might also be a concern.',
    titleReward: 'The Zoologist',
    statKey: 'totalBestiaryCompleted',
    threshold: 5,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  {
    id: 'bestiary_complete_all',
    category: 'bestiary',
    title: 'Encyclopedist',
    description: 'All fifty, mastered. The Encyclopedist. Every creature in the Pocketrealm has been met, measured, and understood. The book is closed. You wrote it.',
    flavorText: 'Every creature in the Pocketrealm, mastered. Every prefix encountered, every variant catalogued, every fight survived and studied. The bestiary is complete, and it is the most thorough document of its kind in existence. Scholars will reference it. Adventurers will carry copies. The creatures themselves, if they could read, would find it uncomfortably accurate. You did not just fight the Pocketrealm\'s bestiary. You became its author.',
    titleReward: 'The Encyclopedist',
    statKey: 'totalBestiaryCompleted',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- General achievements ---
const GENERAL_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'turns_10000',
    category: 'general',
    title: 'Time Invested',
    description: 'Ten thousand turns. You have stopped being a tourist and started being a resident.',
    flavorText: 'Ten thousand turns. That is roughly three hours of real time, give or take, spent doing things that a sensible person would avoid: fighting rats, mining copper, and arguing with the forest about whether its trees are allowed to move. You are not a sensible person. The Pocketrealm appreciates that.',
    statKey: 'totalTurnsSpent',
    threshold: 10000,
  },
  {
    id: 'turns_100000',
    category: 'general',
    title: 'Dedicated Adventurer',
    description: 'A hundred thousand turns, spent willingly. Dedication is not a burst of effort. It is the decision to keep showing up.',
    flavorText: 'One hundred thousand turns. Days of real time spent in the Pocketrealm, measured in swings, steps, and the slow accumulation of experience that turns a wanderer into a fixture. Bram has memorised your order. Maren has saved your seat. Aldric has stopped double-checking your paperwork. You belong here now, in the quiet, permanent way that only time can establish.',
    titleReward: 'The Dedicated',
    statKey: 'totalTurnsSpent',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'turns_1000000',
    category: 'general',
    title: 'No-Lifer',
    description: 'A million turns. The No-Lifer. It sounds like an insult but wears like a crown. You have given this world more time than it had any right to ask for, and it gave you a story worth the investment.',
    flavorText: 'One million turns. The number is absurd and the title is earned. You have fought in every zone, gathered from every node, crafted at every bench, and spent more time in the Pocketrealm than some of its permanent residents. Lira Caravel considers you a supply chain. Rowan Delk considers you a colleague. Gavrik Stoneshoulder considers you proof that individual stubbornness can, given enough time, reshape the world. He is not wrong.',
    titleReward: 'The No-Lifer',
    statKey: 'totalTurnsSpent',
    threshold: 1000000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'recipe_10',
    category: 'general',
    title: 'Cookbook',
    description: 'Ten recipes. Your crafting repertoire has officially outgrown "beginner" and entered "competent." The smoke stains on your clothes confirm it.',
    flavorText: 'Ten recipes committed to memory. Swords, armour, potions, and at least one thing you made by accident that turned out better than anything you made on purpose. The Crafting Quarter is starting to feel like a second home, and Kessa has stopped hovering when you use the forge.',
    statKey: 'totalRecipesLearned',
    threshold: 10,
  },
  {
    id: 'recipe_25',
    category: 'general',
    title: 'Recipe Collector',
    description: 'Twenty-five recipes, collected one by one. The Collector. You do not just know how to make things. You know how to make nearly everything.',
    flavorText: 'Twenty-five recipes. You can make weapons from five different metals, brew potions from herbs that most people cannot pronounce, and tan leather that even the bog refuses to rot. The knowledge is not written down anywhere complete; it lives in your hands, in the muscle memory of a hundred crafting sessions, in the instinct that tells you when the iron is ready by the colour of the flame rather than the temperature.',
    titleReward: 'The Collector',
    statKey: 'totalRecipesLearned',
    threshold: 25,
    tier: 2,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
  // Secret achievements
  {
    id: 'secret_first_death',
    category: 'general',
    title: 'Humbling Experience',
    description: 'You fell. You got back up. The Pocketrealm does not remember your defeats. It remembers what you did after them.',
    flavorText: 'You lost. Not \'almost lost,\' not \'barely survived,\' but properly, completely, face-in-the-dirt lost. Something in the Pocketrealm hit you harder than you expected, and instead of a victory screen you got a long, quiet walk back to town with nothing but your pride in tatters. This is not a failure. This is a lesson, and it is the most important one the Pocketrealm teaches: you are not invincible. Now get up.',
    statKey: 'totalDeaths',
    threshold: 1,
    secret: true,
  },
  {
    id: 'tutorial_complete',
    category: 'general',
    title: 'The Graduate',
    description: 'Tutorial complete. You know which end of the sword to hold, where the ore goes, and why you should not pet the rats. Everything else, you will learn by doing.',
    flavorText: 'The tutorial is behind you. The training dummies are done, the practice swings have been swung, and someone (probably Rowan Delk, leaning against the gate with his arms crossed) has decided that you are unlikely to die in the first five minutes. This is a low bar. You have cleared it. The Pocketrealm awaits, and it is considerably less patient than the tutorial.',
    titleReward: 'The Graduate',
    statKey: 'tutorialCompleted',
    threshold: 1,
  },
  {
    id: 'secret_legendary_crit',
    category: 'crafting',
    title: 'Golden Hands',
    description: 'Golden Hands. A legendary item, forged through a critical success. Lightning does not strike twice, but it only needed to strike once.',
    flavorText: 'The hammer fell. The metal sang. And something happened that should not have happened: the material transcended itself, the craft transcended the crafter, and what came out of the forge (or the bench, or the loom) was not merely excellent. It was legendary, born from a critical success so improbable that Kessa Ironweld would stop mid-sentence to stare at it. Vesper Tain would set down her flask. Aldric Voss would open a new page in the ledger, specifically. This is the rarest achievement in the Pocketrealm: not earned through grinding, not reached through patience, but produced by a single, unrepeatable moment where everything aligned and the universe held its breath.',
    titleReward: 'Golden Hands',
    statKey: 'totalLegendariesCrafted',
    threshold: 1,
    tier: 5,
    secret: true,
  },
];

// --- Family achievements (generated for all 19 families) ---
const FAMILY_KEYS = [
  'vermin', 'spiders', 'boars', 'wolves', 'bandits',
  'treants', 'spirits', 'fae', 'bats', 'goblins',
  'golems', 'crawlers', 'harpies', 'undead', 'swampBeasts',
  'witches', 'elementals', 'serpents', 'abominations',
] as const;

const FAMILY_DISPLAY_NAMES: Record<string, string> = {
  vermin: 'Vermin',
  spiders: 'Spider',
  boars: 'Boar',
  wolves: 'Wolf',
  bandits: 'Bandit',
  treants: 'Treant',
  spirits: 'Spirit',
  fae: 'Fae',
  bats: 'Bat',
  goblins: 'Goblin',
  golems: 'Golem',
  crawlers: 'Crawler',
  harpies: 'Harpy',
  undead: 'Undead',
  swampBeasts: 'Swamp Beast',
  witches: 'Witch',
  elementals: 'Elemental',
  serpents: 'Serpent',
  abominations: 'Abomination',
};

// Maps family key to the unique item template ID awarded at 1,000 kills
export const FAMILY_REWARD_ITEMS: Record<string, string> = {
  vermin: 'achievement_vermin_gloves',
  spiders: 'achievement_spiders_boots',
  boars: 'achievement_boars_chest',
  wolves: 'achievement_wolves_chest',
  bandits: 'achievement_bandits_weapon',
  treants: 'achievement_treants_shield',
  spirits: 'achievement_spirits_charm',
  fae: 'achievement_fae_ring',
  bats: 'achievement_bats_helm',
  goblins: 'achievement_goblins_helm',
  golems: 'achievement_golems_charm',
  crawlers: 'achievement_crawlers_legs',
  harpies: 'achievement_harpies_boots',
  undead: 'achievement_undead_gloves',
  swampBeasts: 'achievement_swampBeasts_belt',
  witches: 'achievement_witches_helm',
  elementals: 'achievement_elementals_neck',
  serpents: 'achievement_serpents_ring',
  abominations: 'achievement_abominations_chest',
};

const FAMILY_ACHIEVEMENTS: AchievementDef[] = FAMILY_KEYS.flatMap((key) => {
  const name = FAMILY_DISPLAY_NAMES[key];
  return [
    {
      id: `family_${key}_500`,
      category: 'family' as const,
      title: `${name} Hunter`,
      description: `Kill 500 ${name}s`,
      familyKey: key,
      threshold: 500,
      tier: 1,
    },
    {
      id: `family_${key}_2500`,
      category: 'family' as const,
      title: `${name} Slayer`,
      description: `Kill 2,500 ${name}s`,
      titleReward: `${name} Slayer`,
      familyKey: key,
      threshold: 2500,
      tier: 2,
    },
    {
      id: `family_${key}_5000`,
      category: 'family' as const,
      title: `${name}'s Bane`,
      description: `Kill 5,000 ${name}s`,
      titleReward: `${name}'s Bane`,
      familyKey: key,
      threshold: 5000,
      tier: 3,
      rewards: [{ type: 'item', amount: 1, itemTemplateId: FAMILY_REWARD_ITEMS[key] }],
    },
  ];
});

// --- Guild achievements ---
const GUILD_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'guild_level_5',
    category: 'guild',
    title: 'Guild Founder',
    description: 'Guild level 5. You are no longer a group of adventurers with a shared name. You are a guild, and the Pocketrealm has noticed.',
    flavorText: 'Five levels. Your guild has survived its infancy, which in the Pocketrealm means surviving the part where everyone argues about the name, the tax rate, and whose idea it was to recruit that one person who has not logged in since joining. The organisation stage is over. The building stage begins.',
    statKey: 'guildLevel',
    threshold: 5,
  },
  {
    id: 'guild_level_15',
    category: 'guild',
    title: 'Guild Builder',
    description: 'Level 15. Your guild is no longer growing. It is established. The difference is that established things are harder to remove.',
    flavorText: 'Fifteen levels. The guild has a treasury that means something, a roster that holds, and a reputation that precedes it. Contracts come in and get completed. Members contribute without being asked. Gavrik Stoneshoulder has started nodding when your guild\'s name comes up, which from him is the equivalent of a standing ovation.',
    titleReward: 'Guild Builder',
    statKey: 'guildLevel',
    threshold: 15,
    tier: 2,
  },
  {
    id: 'guild_level_30',
    category: 'guild',
    title: 'Guildmaster',
    description: 'Guildmaster. Not a title you claim. A title your guild earned, and you earned by holding it together.',
    flavorText: 'Thirty. Your guild has outlasted quarrels, roster turnover, failed contracts, and at least one treasury crisis that nobody talks about anymore. It has become an institution, the kind of thing that Thornwall\'s guard references in briefings and Millbrook\'s merchants factor into their quarterly projections. Gavrik updates the guild\'s file with his metal hand and a rare smile. The memorial wall behind him has fewer names because of guilds like yours. That is the real achievement.',
    titleReward: 'Guildmaster',
    statKey: 'guildLevel',
    threshold: 30,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'guild_contracts_1',
    category: 'guild',
    title: 'Contract Worker',
    description: 'One contract down. The guild works because people like you show up and do the work that nobody writes songs about.',
    flavorText: 'Your first contract, completed. The bounty was collective, the effort was shared, and the reward went to the treasury rather than your pocket. That is the strange alchemy of guild work: you do more, earn less personally, and somehow feel richer for it. Gavrik calls this \'the point.\' He is, annoyingly, correct.',
    statKey: 'guildContractsCompleted',
    threshold: 1,
  },
  {
    id: 'guild_contracts_10',
    category: 'guild',
    title: 'Contract Specialist',
    description: 'Complete 10 guild contracts',
    titleReward: 'Contractor',
    statKey: 'guildContractsCompleted',
    threshold: 10,
    tier: 2,
  },
  {
    id: 'guild_contracts_50',
    category: 'guild',
    title: 'Contract Legend',
    description: 'Complete 50 guild contracts',
    titleReward: 'The Contractor',
    statKey: 'guildContractsCompleted',
    threshold: 50,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'guild_contrib_10000',
    category: 'guild',
    title: 'Loyal Member',
    description: 'Contribute 10,000 turns to your guild treasury',
    statKey: 'guildTurnsContributed',
    threshold: 10000,
  },
  {
    id: 'guild_contrib_100000',
    category: 'guild',
    title: 'Pillar of the Guild',
    description: 'A hundred thousand turns, given willingly. The Pillar. Every guild needs someone who builds the floor that everyone else stands on. That someone is you.',
    flavorText: 'One hundred thousand turns, donated to the treasury. Not spent on your gear, your potions, or your next forge upgrade. Given, freely, to something larger than yourself. The guild\'s projects run on contributions like yours: the specialisations, the boosts, the upgrades that benefit everyone. You are not the guild\'s strongest fighter or its best crafter. You are something more important. You are its foundation.',
    titleReward: 'Guild Pillar',
    statKey: 'guildTurnsContributed',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'guild_contrib_500000',
    category: 'guild',
    title: 'Guild Patron',
    description: 'Contribute 500,000 turns to your guild treasury',
    titleReward: 'Guild Patron',
    statKey: 'guildTurnsContributed',
    threshold: 500000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
  {
    id: 'guild_members_5',
    category: 'guild',
    title: 'Growing Community',
    description: 'Be in a guild with 5 or more members',
    statKey: 'guildMemberCount',
    threshold: 5,
  },
  {
    id: 'guild_members_15',
    category: 'guild',
    title: 'Popular Guild',
    description: 'Be in a guild with 15 or more members',
    titleReward: 'Recruiter',
    statKey: 'guildMemberCount',
    threshold: 15,
    tier: 2,
  },
  {
    id: 'guild_members_30',
    category: 'guild',
    title: 'Guild Empire',
    description: 'Be in a guild with 30 or more members',
    titleReward: 'Empire Builder',
    statKey: 'guildMemberCount',
    threshold: 30,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 1 }],
  },
];

// --- Casino achievements ---
const CASINO_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'casino_first_bet',
    category: 'casino',
    title: 'Feeling Lucky',
    description: 'Your first wager. The wheel spins for you now. It will spin regardless, but now it does so with your money on the line.',
    flavorText: 'Your first bet. A small number pushed across the table toward a man who smiles for a living. Silas Vane welcomed you to The Gilded Wheel with the warmth of someone who has just acquired a new source of income. Whether you won or lost is beside the point. You sat down. That is the only decision that matters, and it is the one you cannot take back.',
    statKey: 'totalBetsPlaced',
    threshold: 1,
  },
  {
    id: 'casino_wagered_10k',
    category: 'casino',
    title: 'Small Stakes',
    description: 'Wager 10,000 gold total',
    statKey: 'totalGoldWagered',
    threshold: 10000,
  },
  {
    id: 'casino_wagered_100k',
    category: 'casino',
    title: 'High Roller',
    description: 'A hundred thousand wagered. The wheel knows your face, your habits, and the exact weight of your favourite bet. Welcome to the deep end.',
    flavorText: 'One hundred thousand gold, fed to the wheel one bet at a time. You have developed a rhythm: the exchange, the wager, the spin, the result. Win or lose, the process is the same, and you have found a comfort in the repetition that says more about you than the outcome ever could. Silas has started greeting you by name. That is either hospitality or a warning sign.',
    statKey: 'totalGoldWagered',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'casino_wagered_1m',
    category: 'casino',
    title: 'Whale',
    description: 'A million gold wagered. Whale. You are not a gambler anymore. You are an institution, and institutions have titles.',
    flavorText: 'One million gold through the wheel. The number is staggering, and Silas handles it with the casual grace of a man who has seen staggering numbers before and found them all equally useful. You are a whale: the casino\'s most valued species, distinguished by volume rather than luck. The title sounds like mockery. It is not. Whales keep the lights on, and The Gilded Wheel\'s lights have never been brighter.',
    titleReward: 'Whale',
    statKey: 'totalGoldWagered',
    threshold: 1000000,
    tier: 3,
  },
  {
    id: 'casino_wagered_10m',
    category: 'casino',
    title: 'The House',
    description: 'Ten million. The House. The title belongs to the casino, and now it belongs to you. Silas considers this a partnership. He has never been more sincere.',
    flavorText: 'Ten million gold. The number has transcended money and become a philosophical statement about the nature of entertainment, risk, and the peculiar human impulse to convert certainty into possibility and call the exchange worthwhile. Silas Vane does not smile when you sit down anymore. He nods. The nod says: you and I are the same. We both live by the wheel. The difference is that I built it and you keep spinning it, and neither of us can stop. The House always wins. But which house are we talking about?',
    titleReward: 'The House',
    statKey: 'totalGoldWagered',
    threshold: 10000000,
    tier: 5,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
  {
    id: 'casino_exchanged_10k',
    category: 'casino',
    title: 'Gold Rush',
    description: 'Exchange 10,000 turns for gold',
    statKey: 'totalTurnsExchanged',
    threshold: 10000,
  },
  {
    id: 'casino_exchanged_100k',
    category: 'casino',
    title: 'Minted',
    description: 'Exchange 100,000 turns for gold',
    statKey: 'totalTurnsExchanged',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'casino_exchanged_1m',
    category: 'casino',
    title: 'Gold Standard',
    description: 'Exchange 1,000,000 turns for gold',
    titleReward: 'Minted',
    statKey: 'totalTurnsExchanged',
    threshold: 1000000,
    tier: 3,
    rewards: [{ type: 'attribute_points', amount: 2 }],
  },
  {
    id: 'casino_gold_100k',
    category: 'casino',
    title: 'Jackpot',
    description: 'A hundred thousand gold, all at once. Jackpot. For one shining moment, you are the richest person in the room. Enjoy it before the wheel gets ideas.',
    flavorText: 'One hundred thousand gold in your possession at the same time. Not wagered, not spent, not lost. Held. The weight of it (metaphorical, since gold in the Pocketrealm does not actually weigh anything, which is a separate conversation) changes how you walk through Thornwall. Lira Caravel treats you differently. Silas watches you more carefully. Having money is a statement. Having this much money is an argument.',
    statKey: 'peakGoldHeld',
    threshold: 100000,
    tier: 2,
  },
  {
    id: 'casino_gold_1m',
    category: 'casino',
    title: 'Fortune',
    description: 'A million gold, held at the same time. Fortune. The title is earned not by spending but by not spending, which in the Pocketrealm is the harder skill by far.',
    flavorText: 'One million gold. At once. In your pocket (again, metaphorically; the pocket in question would need to be geological). You have achieved a level of wealth that Bram Holloway cannot comprehend, Lira Caravel envies professionally, and Silas Vane considers a personal challenge. The gold is not the achievement. The restraint required to accumulate it without spending it is. In a world that asks you to invest every resource into survival, you found a way to hoard a million of them and still be standing. That is not luck. That is discipline wearing a very expensive hat.',
    titleReward: 'Fortunate',
    statKey: 'peakGoldHeld',
    threshold: 1000000,
    tier: 4,
    rewards: [{ type: 'attribute_points', amount: 3 }],
  },
];

// --- Shop achievements (unlocked by quest shop purchase, not stats) ---
const SHOP_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: PREMIUM_CONSTANTS.SUPPORT_TITLE_ACHIEVEMENT_ID,
    category: 'shop',
    title: 'Support Pocketrealm',
    description: 'Support Pocketrealm and unlock the Champion title.',
    titleReward: PREMIUM_CONSTANTS.SUPPORT_TITLE,
    threshold: 0,
    tier: 5,
  },
  {
    id: 'shop_title_questmaster',
    category: 'shop',
    title: 'Questmaster',
    description: 'Purchase the Questmaster title from the quest shop',
    titleReward: 'Questmaster',
    threshold: 0,
    tier: 4,
  },
  {
    id: 'shop_title_token_hoarder',
    category: 'shop',
    title: 'Token Hoarder',
    description: 'Purchase the Token Hoarder title from the quest shop',
    titleReward: 'Token Hoarder',
    threshold: 0,
    tier: 5,
  },
];

export const ALL_ACHIEVEMENTS: AchievementDef[] = [
  ...COMBAT_ACHIEVEMENTS,
  ...EXPLORATION_ACHIEVEMENTS,
  ...CRAFTING_ACHIEVEMENTS,
  ...SKILLS_ACHIEVEMENTS,
  ...GATHERING_ACHIEVEMENTS,
  ...BESTIARY_ACHIEVEMENTS,
  ...GENERAL_ACHIEVEMENTS,
  ...FAMILY_ACHIEVEMENTS,
  ...GUILD_ACHIEVEMENTS,
  ...CASINO_ACHIEVEMENTS,
  ...SHOP_ACHIEVEMENTS,
];

// Lookup maps for efficient access
export const ACHIEVEMENTS_BY_ID = new Map(ALL_ACHIEVEMENTS.map((a) => [a.id, a]));
export const ACHIEVEMENTS_BY_STAT_KEY = new Map<string, AchievementDef[]>();
export const ACHIEVEMENTS_BY_FAMILY_KEY = new Map<string, AchievementDef[]>();

for (const a of ALL_ACHIEVEMENTS) {
  if (a.statKey) {
    const list = ACHIEVEMENTS_BY_STAT_KEY.get(a.statKey) ?? [];
    list.push(a);
    ACHIEVEMENTS_BY_STAT_KEY.set(a.statKey, list);
  }
  if (a.familyKey) {
    const list = ACHIEVEMENTS_BY_FAMILY_KEY.get(a.familyKey) ?? [];
    list.push(a);
    ACHIEVEMENTS_BY_FAMILY_KEY.set(a.familyKey, list);
  }
}
