import type { TalentNodeDefinition, TalentTree } from '../types/combatAction.types';

// =============================================================================
// MELEE TREE (18 nodes: 4×T1-T4 + 2×T5)
// =============================================================================

const meleeNodes: TalentNodeDefinition[] = [
  // Tier 1
  {
    id: 'melee_power_strike',
    tree: 'melee',
    tier: 1,
    name: 'Power Strike',
    description: 'A focused strike with extra force behind it.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'power_strike',
  },
  {
    id: 'melee_rending_slash',
    tree: 'melee',
    tier: 1,
    name: 'Rending Slash',
    description: 'A brutal slash that causes deep bleeding.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'rending_slash',
  },
  {
    id: 'melee_iron_skin',
    tree: 'melee',
    tier: 1,
    name: 'Iron Skin',
    description: 'Toughened body grants passive defence bonus.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'defence', value: 5, isPercent: true, description: '+5% defence' },
  },
  {
    id: 'melee_endurance_training',
    tree: 'melee',
    tier: 1,
    name: 'Endurance Training',
    description: 'Increased stamina pool through physical conditioning.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'maxStamina', value: 10, isPercent: true, description: '+10% stamina pool' },
  },
  // Tier 2 (requires melee 15)
  {
    id: 'melee_cleave',
    tree: 'melee',
    tier: 2,
    name: 'Cleave',
    description: 'A wide swing that hits all enemies in raids.',
    pointCost: 10,
    skillLevelGate: { skill: 'melee', level: 15 },
    prerequisites: ['melee_power_strike'],
    unlocksAction: 'cleave',
  },
  {
    id: 'melee_venomous_strike',
    tree: 'melee',
    tier: 2,
    name: 'Venomous Strike',
    description: 'Coat your weapon in poison, applying a lingering toxin.',
    pointCost: 10,
    skillLevelGate: { skill: 'melee', level: 15 },
    prerequisites: ['melee_rending_slash'],
    unlocksAction: 'venomous_strike',
  },
  {
    id: 'melee_battle_cry',
    tree: 'melee',
    tier: 2,
    name: 'Battle Cry',
    description: 'A war cry that boosts attack power.',
    pointCost: 10,
    skillLevelGate: { skill: 'melee', level: 15 },
    prerequisites: ['melee_iron_skin'],
    unlocksAction: 'battle_cry',
  },
  {
    id: 'melee_stamina_surge',
    tree: 'melee',
    tier: 2,
    name: 'Stamina Surge',
    description: 'Improved stamina recovery during combat.',
    pointCost: 10,
    skillLevelGate: { skill: 'melee', level: 15 },
    prerequisites: ['melee_endurance_training'],
    passiveBonus: { stat: 'staminaRegen', value: 15, isPercent: true, description: '+15% stamina regen' },
  },
  // Tier 3 (requires melee 35)
  {
    id: 'melee_devastating_blow',
    tree: 'melee',
    tier: 3,
    name: 'Devastating Blow',
    description: 'A devastating overhead strike. Leaves you open.',
    pointCost: 20,
    skillLevelGate: { skill: 'melee', level: 35 },
    prerequisites: ['melee_cleave'],
    unlocksAction: 'devastating_blow',
  },
  {
    id: 'melee_whirlwind',
    tree: 'melee',
    tier: 3,
    name: 'Whirlwind',
    description: 'A spinning strike hitting all enemies in raids.',
    pointCost: 20,
    skillLevelGate: { skill: 'melee', level: 35 },
    prerequisites: ['melee_cleave'],
    unlocksAction: 'whirlwind',
  },
  {
    id: 'melee_berserker_rage',
    tree: 'melee',
    tier: 3,
    name: 'Berserker Rage',
    description: 'Enter a frenzy, greatly boosting attack power.',
    pointCost: 20,
    skillLevelGate: { skill: 'melee', level: 35 },
    prerequisites: ['melee_battle_cry'],
    unlocksAction: 'berserker_rage',
  },
  {
    id: 'melee_weapon_mastery',
    tree: 'melee',
    tier: 3,
    name: 'Weapon Mastery',
    description: 'Deep weapon training increases all weapon damage.',
    pointCost: 20,
    skillLevelGate: { skill: 'melee', level: 35 },
    prerequisites: ['melee_stamina_surge'],
    passiveBonus: { stat: 'weaponDamage', value: 10, isPercent: true, description: '+10% weapon damage' },
  },
  // Tier 4 (requires melee 60)
  {
    id: 'melee_execute',
    tree: 'melee',
    tier: 4,
    name: 'Execute',
    description: 'A finishing strike that deals bonus damage to wounded targets.',
    pointCost: 35,
    skillLevelGate: { skill: 'melee', level: 60 },
    prerequisites: ['melee_devastating_blow'],
    unlocksAction: 'execute',
  },
  {
    id: 'melee_flame_sword',
    tree: 'melee',
    tier: 4,
    name: 'Flame Sword',
    description: 'Engulf your blade in fire, dealing magic damage that bypasses physical armour.',
    pointCost: 35,
    skillLevelGate: { skill: 'melee', level: 60 },
    prerequisites: ['melee_weapon_mastery'],
    unlocksAction: 'flame_sword',
  },
  {
    id: 'melee_unbreakable',
    tree: 'melee',
    tier: 4,
    name: 'Unbreakable',
    description: 'Hardened constitution grants a massive HP bonus.',
    pointCost: 35,
    skillLevelGate: { skill: 'melee', level: 60 },
    prerequisites: ['melee_berserker_rage'],
    passiveBonus: { stat: 'maxHp', value: 20, isPercent: true, description: '+20% max HP' },
  },
  {
    id: 'melee_iron_will',
    tree: 'melee',
    tier: 4,
    name: 'Iron Will',
    description: 'Mental fortitude reduces debuff duration.',
    pointCost: 35,
    skillLevelGate: { skill: 'melee', level: 60 },
    prerequisites: ['melee_weapon_mastery'],
    passiveBonus: { stat: 'debuffDuration', value: -1, description: 'Reduce debuff duration by 1 round' },
  },
  // Tier 5 (requires melee 85)
  {
    id: 'melee_titans_wrath',
    tree: 'melee',
    tier: 5,
    name: "Titan's Wrath",
    description: 'Ultimate melee strike of devastating power. Leaves you open.',
    pointCost: 50,
    skillLevelGate: { skill: 'melee', level: 85 },
    prerequisites: ['melee_execute'],
    unlocksAction: 'titans_wrath',
  },
  {
    id: 'melee_champions_resolve',
    tree: 'melee',
    tier: 5,
    name: "Champion's Resolve",
    description: 'Peak physical conditioning boosts stamina regen and pool.',
    pointCost: 50,
    skillLevelGate: { skill: 'melee', level: 85 },
    prerequisites: ['melee_unbreakable', 'melee_iron_will'],
    passiveBonus: { stat: 'staminaRegenAndPool', value: 25, isPercent: true, description: '+25% stamina regen + pool' },
  },
];

// =============================================================================
// RANGED TREE (18 nodes: 4×T1-T4 + 2×T5)
// =============================================================================

const rangedNodes: TalentNodeDefinition[] = [
  // Tier 1
  {
    id: 'ranged_aimed_shot',
    tree: 'ranged',
    tier: 1,
    name: 'Aimed Shot',
    description: 'A carefully aimed shot with increased damage.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'aimed_shot',
  },
  {
    id: 'ranged_barbed_arrow',
    tree: 'ranged',
    tier: 1,
    name: 'Barbed Arrow',
    description: 'A serrated arrowhead tears flesh, causing deep bleeding.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'barbed_arrow',
  },
  {
    id: 'ranged_quick_draw',
    tree: 'ranged',
    tier: 1,
    name: 'Quick Draw',
    description: 'Faster weapon handling increases critical chance.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'critChance', value: 5, isPercent: true, description: '+5% crit chance' },
  },
  {
    id: 'ranged_keen_eye',
    tree: 'ranged',
    tier: 1,
    name: 'Keen Eye',
    description: 'Sharper focus increases accuracy.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'accuracy', value: 10, isPercent: true, description: '+10% accuracy' },
  },
  // Tier 2 (requires ranged 15)
  {
    id: 'ranged_scatter_shot',
    tree: 'ranged',
    tier: 2,
    name: 'Scatter Shot',
    description: 'A spread of arrows hitting all enemies and reducing their accuracy in raids.',
    pointCost: 10,
    skillLevelGate: { skill: 'ranged', level: 15 },
    prerequisites: ['ranged_aimed_shot'],
    unlocksAction: 'scatter_shot',
  },
  {
    id: 'ranged_crippling_shot',
    tree: 'ranged',
    tier: 2,
    name: 'Crippling Shot',
    description: 'A precise shot that pins the target, forcing them to defend next turn.',
    pointCost: 10,
    skillLevelGate: { skill: 'ranged', level: 15 },
    prerequisites: ['ranged_barbed_arrow'],
    unlocksAction: 'crippling_shot',
  },
  {
    id: 'ranged_eagle_eye',
    tree: 'ranged',
    tier: 2,
    name: 'Eagle Eye',
    description: 'Intense focus grants a massive accuracy boost.',
    pointCost: 10,
    skillLevelGate: { skill: 'ranged', level: 15 },
    prerequisites: ['ranged_keen_eye'],
    unlocksAction: 'eagle_eye',
  },
  {
    id: 'ranged_steady_hands',
    tree: 'ranged',
    tier: 2,
    name: 'Steady Hands',
    description: 'Improved precision increases critical damage.',
    pointCost: 10,
    skillLevelGate: { skill: 'ranged', level: 15 },
    prerequisites: ['ranged_quick_draw'],
    passiveBonus: { stat: 'critDamage', value: 15, isPercent: true, description: '+15% crit damage' },
  },
  // Tier 3 (requires ranged 35)
  {
    id: 'ranged_volley',
    tree: 'ranged',
    tier: 3,
    name: 'Volley',
    description: 'A rain of arrows that suppresses all enemies in raids.',
    pointCost: 20,
    skillLevelGate: { skill: 'ranged', level: 35 },
    prerequisites: ['ranged_scatter_shot'],
    unlocksAction: 'volley',
  },
  {
    id: 'ranged_snipers_mark',
    tree: 'ranged',
    tier: 3,
    name: "Sniper's Mark",
    description: 'Mark a target, reducing their evasion. Always hits.',
    pointCost: 20,
    skillLevelGate: { skill: 'ranged', level: 35 },
    prerequisites: ['ranged_eagle_eye'],
    unlocksAction: 'snipers_mark',
  },
  {
    id: 'ranged_flame_arrow',
    tree: 'ranged',
    tier: 3,
    name: 'Flame Arrow',
    description: 'Ignite your arrow, scorching the target on impact.',
    pointCost: 20,
    skillLevelGate: { skill: 'ranged', level: 35 },
    prerequisites: ['ranged_steady_hands'],
    unlocksAction: 'flame_arrow',
  },
  {
    id: 'ranged_evasive_maneuver',
    tree: 'ranged',
    tier: 3,
    name: 'Evasive Maneuver',
    description: 'Combat agility increases dodge chance.',
    pointCost: 20,
    skillLevelGate: { skill: 'ranged', level: 35 },
    prerequisites: ['ranged_steady_hands'],
    passiveBonus: { stat: 'dodge', value: 10, isPercent: true, description: '+10% dodge' },
  },
  // Tier 4 (requires ranged 60)
  {
    id: 'ranged_piercing_shot',
    tree: 'ranged',
    tier: 4,
    name: 'Piercing Shot',
    description: 'An armour-piercing shot that punches through defences.',
    pointCost: 35,
    skillLevelGate: { skill: 'ranged', level: 60 },
    prerequisites: ['ranged_volley'],
    unlocksAction: 'piercing_shot',
  },
  {
    id: 'ranged_shadow_arrow',
    tree: 'ranged',
    tier: 4,
    name: 'Shadow Arrow',
    description: 'An arrow infused with dark energy that siphons life on impact.',
    pointCost: 35,
    skillLevelGate: { skill: 'ranged', level: 60 },
    prerequisites: ['ranged_flame_arrow'],
    unlocksAction: 'shadow_arrow',
  },
  {
    id: 'ranged_quick_reflexes',
    tree: 'ranged',
    tier: 4,
    name: 'Quick Reflexes',
    description: 'Faster reactions reduce Counter stamina cost.',
    pointCost: 35,
    skillLevelGate: { skill: 'ranged', level: 60 },
    prerequisites: ['ranged_snipers_mark'],
    passiveBonus: { stat: 'counterCost', value: -10, description: 'Counter costs -10 stamina' },
  },
  {
    id: 'ranged_fleet_foot',
    tree: 'ranged',
    tier: 4,
    name: 'Fleet Foot',
    description: 'Superior agility increases evasion.',
    pointCost: 35,
    skillLevelGate: { skill: 'ranged', level: 60 },
    prerequisites: ['ranged_evasive_maneuver'],
    passiveBonus: { stat: 'evasion', value: 15, isPercent: true, description: '+15% evasion' },
  },
  // Tier 5 (requires ranged 85)
  {
    id: 'ranged_death_mark',
    tree: 'ranged',
    tier: 5,
    name: 'Death Mark',
    description: 'Ultimate ranged shot that marks the target for death.',
    pointCost: 50,
    skillLevelGate: { skill: 'ranged', level: 85 },
    prerequisites: ['ranged_piercing_shot'],
    unlocksAction: 'death_mark',
  },
  {
    id: 'ranged_windwalker',
    tree: 'ranged',
    tier: 5,
    name: 'Windwalker',
    description: 'One with the wind — massive dodge and evasion bonus.',
    pointCost: 50,
    skillLevelGate: { skill: 'ranged', level: 85 },
    prerequisites: ['ranged_quick_reflexes', 'ranged_fleet_foot'],
    passiveBonus: { stat: 'dodgeAndEvasion', value: 25, isPercent: true, description: '+25% dodge + evasion' },
  },
];

// =============================================================================
// MAGIC TREE (18 nodes: 4×T1-T4 + 2×T5)
// =============================================================================

const magicNodes: TalentNodeDefinition[] = [
  // Tier 1
  {
    id: 'magic_fire_bolt',
    tree: 'magic',
    tier: 1,
    name: 'Fire Bolt',
    description: 'Hurl a bolt of fire dealing magic damage.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'fire_bolt',
  },
  {
    id: 'magic_enfeeble',
    tree: 'magic',
    tier: 1,
    name: 'Enfeeble',
    description: "Sap the target's strength, reducing their attack power.",
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'enfeeble',
  },
  {
    id: 'magic_minor_heal',
    tree: 'magic',
    tier: 1,
    name: 'Minor Heal',
    description: 'Channel healing energy to restore HP.',
    pointCost: 5,
    prerequisites: [],
    unlocksAction: 'minor_heal',
  },
  {
    id: 'magic_arcane_focus',
    tree: 'magic',
    tier: 1,
    name: 'Arcane Focus',
    description: 'Deeper mana reserves through arcane study.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'maxMana', value: 10, isPercent: true, description: '+10% mana pool' },
  },
  // Tier 2 (requires magic 15)
  {
    id: 'magic_frost_nova',
    tree: 'magic',
    tier: 2,
    name: 'Frost Nova',
    description: 'A blast of frost that freezes all enemies in raids.',
    pointCost: 10,
    skillLevelGate: { skill: 'magic', level: 15 },
    prerequisites: ['magic_fire_bolt'],
    unlocksAction: 'frost_nova',
  },
  {
    id: 'magic_curse',
    tree: 'magic',
    tier: 2,
    name: 'Curse',
    description: 'Curse the target, weakening their magical defences.',
    pointCost: 10,
    skillLevelGate: { skill: 'magic', level: 15 },
    prerequisites: ['magic_enfeeble'],
    unlocksAction: 'curse',
  },
  {
    id: 'magic_enhanced_fortitude',
    tree: 'magic',
    tier: 2,
    name: 'Enhanced Fortitude',
    description: 'A magical barrier that boosts defence.',
    pointCost: 10,
    skillLevelGate: { skill: 'magic', level: 15 },
    prerequisites: ['magic_minor_heal'],
    unlocksAction: 'enhanced_fortitude',
  },
  {
    id: 'magic_mana_flow',
    tree: 'magic',
    tier: 2,
    name: 'Mana Flow',
    description: 'Improved mana circulation increases regen.',
    pointCost: 10,
    skillLevelGate: { skill: 'magic', level: 15 },
    prerequisites: ['magic_arcane_focus'],
    passiveBonus: { stat: 'manaRegen', value: 15, isPercent: true, description: '+15% mana regen' },
  },
  // Tier 3 (requires magic 35)
  {
    id: 'magic_blizzard',
    tree: 'magic',
    tier: 3,
    name: 'Blizzard',
    description: 'A storm of ice hitting all enemies and freezing them in raids.',
    pointCost: 20,
    skillLevelGate: { skill: 'magic', level: 35 },
    prerequisites: ['magic_frost_nova'],
    unlocksAction: 'blizzard',
  },
  {
    id: 'magic_earth_spikes',
    tree: 'magic',
    tier: 3,
    name: 'Earth Spikes',
    description: 'Conjure jagged stone that pierces armour, dealing physical damage.',
    pointCost: 20,
    skillLevelGate: { skill: 'magic', level: 35 },
    prerequisites: ['magic_mana_flow'],
    unlocksAction: 'earth_spikes',
  },
  {
    id: 'magic_heal_ally',
    tree: 'magic',
    tier: 3,
    name: 'Heal Ally',
    description: 'Powerful healing spell targeting an ally in raids.',
    pointCost: 20,
    skillLevelGate: { skill: 'magic', level: 35 },
    prerequisites: ['magic_enhanced_fortitude'],
    unlocksAction: 'heal_ally',
  },
  {
    id: 'magic_spell_penetration',
    tree: 'magic',
    tier: 3,
    name: 'Spell Penetration',
    description: 'Spells bypass a portion of magic defence.',
    pointCost: 20,
    skillLevelGate: { skill: 'magic', level: 35 },
    prerequisites: ['magic_mana_flow'],
    passiveBonus: { stat: 'magicPenetration', value: 15, isPercent: true, description: 'Ignore 15% magic defence' },
  },
  // Tier 4 (requires magic 60)
  {
    id: 'magic_arcane_blast',
    tree: 'magic',
    tier: 4,
    name: 'Arcane Blast',
    description: 'Concentrated arcane energy dealing heavy magic damage.',
    pointCost: 35,
    skillLevelGate: { skill: 'magic', level: 60 },
    prerequisites: ['magic_blizzard'],
    unlocksAction: 'arcane_blast',
  },
  {
    id: 'magic_life_drain',
    tree: 'magic',
    tier: 4,
    name: 'Life Drain',
    description: "Siphon the target's life force to heal yourself.",
    pointCost: 35,
    skillLevelGate: { skill: 'magic', level: 60 },
    prerequisites: ['magic_spell_penetration'],
    unlocksAction: 'life_drain',
  },
  {
    id: 'magic_regeneration',
    tree: 'magic',
    tier: 4,
    name: 'Regeneration',
    description: 'Healing magic that restores HP over time.',
    pointCost: 35,
    skillLevelGate: { skill: 'magic', level: 60 },
    prerequisites: ['magic_heal_ally'],
    unlocksAction: 'regeneration',
  },
  {
    id: 'magic_mind_shield',
    tree: 'magic',
    tier: 4,
    name: 'Mind Shield',
    description: 'Mental barriers reduce Ward mana cost.',
    pointCost: 35,
    skillLevelGate: { skill: 'magic', level: 60 },
    prerequisites: ['magic_spell_penetration'],
    passiveBonus: { stat: 'wardCost', value: -10, description: 'Ward costs -10 mana' },
  },
  // Tier 5 (requires magic 85)
  {
    id: 'magic_meteor_strike',
    tree: 'magic',
    tier: 5,
    name: 'Meteor Strike',
    description: 'Call down a meteor dealing massive AoE magic damage. Leaves you open.',
    pointCost: 50,
    skillLevelGate: { skill: 'magic', level: 85 },
    prerequisites: ['magic_arcane_blast'],
    unlocksAction: 'meteor_strike',
  },
  {
    id: 'magic_archmage',
    tree: 'magic',
    tier: 5,
    name: 'Archmage',
    description: 'Peak arcane mastery boosts mana regen and pool.',
    pointCost: 50,
    skillLevelGate: { skill: 'magic', level: 85 },
    prerequisites: ['magic_regeneration', 'magic_mind_shield'],
    passiveBonus: { stat: 'manaRegenAndPool', value: 25, isPercent: true, description: '+25% mana regen + pool' },
  },
];

// =============================================================================
// SURVIVAL TREE (14 nodes: 3×T1-T4 + 2×T5)
// =============================================================================

const survivalNodes: TalentNodeDefinition[] = [
  // Tier 1
  {
    id: 'survival_improved_defend',
    tree: 'survival',
    tier: 1,
    name: 'Improved Defend',
    description: 'Defend reduces 45% damage instead of 35%.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'defendReduction', value: 0.10, description: 'Defend reduces 45% instead of 35%' },
  },
  {
    id: 'survival_first_aid',
    tree: 'survival',
    tier: 1,
    name: 'First Aid',
    description: 'Better potion application increases effectiveness.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'potionEffectiveness', value: 10, isPercent: true, description: '+10% potion effectiveness' },
  },
  {
    id: 'survival_toughness',
    tree: 'survival',
    tier: 1,
    name: 'Toughness',
    description: 'Hardier constitution grants extra HP.',
    pointCost: 5,
    prerequisites: [],
    passiveBonus: { stat: 'maxHp', value: 5, isPercent: true, description: '+5% max HP' },
  },
  // Tier 2
  {
    id: 'survival_taunt',
    tree: 'survival',
    tier: 2,
    name: 'Taunt',
    description: 'Force a boss to target you. Raid only.',
    pointCost: 10,
    prerequisites: ['survival_toughness'],
    unlocksAction: 'taunt',
  },
  {
    id: 'survival_quick_recovery',
    tree: 'survival',
    tier: 2,
    name: 'Quick Recovery',
    description: 'Faster metabolism reduces potion sickness duration.',
    pointCost: 10,
    prerequisites: ['survival_first_aid'],
    passiveBonus: { stat: 'potionSickness', value: -1, description: 'Reduce potion sickness by 1 round' },
  },
  {
    id: 'survival_resourceful',
    tree: 'survival',
    tier: 2,
    name: 'Resourceful',
    description: 'Efficient resource usage improves both stamina and mana regen.',
    pointCost: 10,
    prerequisites: ['survival_improved_defend'],
    passiveBonus: { stat: 'allRegen', value: 10, isPercent: true, description: '+10% stamina + mana regen' },
  },
  // Tier 3
  {
    id: 'survival_fortify',
    tree: 'survival',
    tier: 3,
    name: 'Fortify',
    description: 'Magical fortification that boosts defence and magic defence.',
    pointCost: 20,
    prerequisites: ['survival_taunt', 'survival_resourceful'],
    unlocksAction: 'fortify',
  },
  {
    id: 'survival_brace',
    tree: 'survival',
    tier: 3,
    name: 'Brace',
    description: 'Brace for impact, reducing physical damage taken.',
    pointCost: 20,
    prerequisites: ['survival_quick_recovery'],
    passiveBonus: { stat: 'physicalDamageReduction', value: 10, isPercent: true, description: '+10% physical damage reduction' },
  },
  {
    id: 'survival_second_wind',
    tree: 'survival',
    tier: 3,
    name: 'Second Wind',
    description: 'Regenerate HP when health is critical.',
    pointCost: 20,
    prerequisites: ['survival_quick_recovery'],
    passiveBonus: { stat: 'lowHpRegen', value: 3, isPercent: true, description: 'Regen 3% max HP/rd when below 40% HP' },
  },
  // Tier 4
  {
    id: 'survival_last_stand',
    tree: 'survival',
    tier: 4,
    name: 'Last Stand',
    description: 'When HP drops below 20%, gain +30% defence for 2 rounds. Once per fight.',
    pointCost: 35,
    prerequisites: ['survival_fortify'],
    passiveBonus: { stat: 'lastStand', value: 1, description: 'Trigger +30% defence at low HP (once per fight)' },
  },
  {
    id: 'survival_rally',
    tree: 'survival',
    tier: 4,
    name: 'Rally',
    description: 'Rally allies, boosting the whole group\'s defence.',
    pointCost: 35,
    prerequisites: ['survival_brace'],
    unlocksAction: 'rally',
  },
  {
    id: 'survival_thick_skin',
    tree: 'survival',
    tier: 4,
    name: 'Thick Skin',
    description: 'Toughened hide reduces magic damage taken.',
    pointCost: 35,
    prerequisites: ['survival_second_wind'],
    passiveBonus: { stat: 'magicDamageReduction', value: 10, isPercent: true, description: '+10% magic damage reduction' },
  },
  // Tier 5
  {
    id: 'survival_undying',
    tree: 'survival',
    tier: 5,
    name: 'Undying',
    description: 'Survive a lethal hit once per fight with 1 HP.',
    pointCost: 50,
    prerequisites: ['survival_last_stand'],
    passiveBonus: { stat: 'undying', value: 1, description: 'Survive lethal hit once per fight with 1 HP' },
  },
  {
    id: 'survival_bulwark',
    tree: 'survival',
    tier: 5,
    name: 'Bulwark',
    description: 'An immovable fortress — increased HP and defence.',
    pointCost: 50,
    prerequisites: ['survival_rally', 'survival_thick_skin'],
    passiveBonus: { stat: 'bulwark', value: 1, description: '+15% max HP, +10% defence' },
  },
];

// =============================================================================
// EXPORTS
// =============================================================================

export const TALENT_TREE_DEFINITIONS: Record<TalentTree, TalentNodeDefinition[]> = {
  melee: meleeNodes,
  ranged: rangedNodes,
  magic: magicNodes,
  survival: survivalNodes,
};

export function getAllTalentNodes(): TalentNodeDefinition[] {
  return [
    ...meleeNodes,
    ...rangedNodes,
    ...magicNodes,
    ...survivalNodes,
  ];
}

const nodeIndex = new Map<string, TalentNodeDefinition>();
for (const nodes of Object.values(TALENT_TREE_DEFINITIONS)) {
  for (const node of nodes) {
    nodeIndex.set(node.id, node);
  }
}

export function getTalentNode(nodeId: string): TalentNodeDefinition | undefined {
  return nodeIndex.get(nodeId);
}
