import { randomUUID } from 'crypto';

// All seed IDs generated once, referenced by variable name across data modules.

export const IDS = {
  // ── Zones ──────────────────────────────────────────────────────────────────
  zones: {
    millbrook: randomUUID(),
    forestEdge: randomUUID(),
    deepForest: randomUUID(),
    caveEntrance: randomUUID(),
    ancientGrove: randomUUID(),
    deepMines: randomUUID(),
    whisperingPlains: randomUUID(),
    thornwall: randomUUID(),
    hauntedMarsh: randomUUID(),
    crystalCaverns: randomUUID(),
    sunkenRuins: randomUUID(),
  },

  // ── Mob Families ───────────────────────────────────────────────────────────
  families: {
    vermin: randomUUID(),
    spiders: randomUUID(),
    boars: randomUUID(),
    wolves: randomUUID(),
    bandits: randomUUID(),
    treants: randomUUID(),
    spirits: randomUUID(),
    fae: randomUUID(),
    bats: randomUUID(),
    goblins: randomUUID(),
    golems: randomUUID(),
    crawlers: randomUUID(),
    harpies: randomUUID(),
    undead: randomUUID(),
    swampBeasts: randomUUID(),
    witches: randomUUID(),
    elementals: randomUUID(),
    serpents: randomUUID(),
    abominations: randomUUID(),
  },

  // ── Item Templates: Raw Resources ─────────────────────────────────────────
  res: {
    copperOre: randomUUID(),
    tinOre: randomUUID(),
    ironOre: randomUUID(),
    sandstone: randomUUID(),
    darkIronOre: randomUUID(),
    mithrilOre: randomUUID(),
    ancientOre: randomUUID(),
    oakLog: randomUUID(),
    mapleLog: randomUUID(),
    fungalWood: randomUUID(),
    elderwoodLog: randomUUID(),
    willowLog: randomUUID(),
    bogwoodLog: randomUUID(),
    crystalWood: randomUUID(),
    petrifiedWood: randomUUID(),
    forestSage: randomUUID(),
    moonpetal: randomUUID(),
    caveMoss: randomUUID(),
    starbloom: randomUUID(),
    glowcapMushroom: randomUUID(),
    windbloom: randomUUID(),
    gravemoss: randomUUID(),
    shimmerFern: randomUUID(),
    abyssalKelp: randomUUID(),
  },

  // ── Item Templates: Raw & Cut Gems ──────────────────────────────────────────
  gems: {
    // Raw gems (gathering crits) — mining
    roughRuby: randomUUID(),
    roughSapphire: randomUUID(),
    roughEmerald: randomUUID(),
    roughDiamond: randomUUID(),
    roughOpal: randomUUID(),
    // Raw gems — foraging
    rawAmber: randomUUID(),
    rawPearl: randomUUID(),
    rawJade: randomUUID(),
    rawMoonstone: randomUUID(),
    rawStarcrystal: randomUUID(),
    // Raw gems — woodcutting
    treeResin: randomUUID(),
    fossilizedSap: randomUUID(),
    crystalBark: randomUUID(),
    heartwoodGem: randomUUID(),
    ancientAmber: randomUUID(),
    // Cut gems — mining
    cutRuby: randomUUID(),
    cutSapphire: randomUUID(),
    cutEmerald: randomUUID(),
    cutDiamond: randomUUID(),
    cutOpal: randomUUID(),
    // Cut gems — foraging
    cutAmber: randomUUID(),
    cutPearl: randomUUID(),
    cutJade: randomUUID(),
    cutMoonstone: randomUUID(),
    cutStarcrystal: randomUUID(),
    // Cut gems — woodcutting
    cutResin: randomUUID(),
    cutSap: randomUUID(),
    cutBark: randomUUID(),
    cutHeartwood: randomUUID(),
    cutAncientAmber: randomUUID(),
  },

  // ── Item Templates: Processed Materials ───────────────────────────────────
  proc: {
    copperIngot: randomUUID(),
    tinIngot: randomUUID(),
    ironIngot: randomUUID(),
    cutStone: randomUUID(),
    darkIronIngot: randomUUID(),
    mithrilIngot: randomUUID(),
    ancientIngot: randomUUID(),
    oakPlank: randomUUID(),
    maplePlank: randomUUID(),
    fungalPlank: randomUUID(),
    elderwoodPlank: randomUUID(),
    willowPlank: randomUUID(),
    bogwoodPlank: randomUUID(),
    crystalPlank: randomUUID(),
    petrifiedPlank: randomUUID(),
  },

  // ── Item Templates: Boss Trophy Materials ─────────────────────────────────
  trophy: {
    alphaWolfFang: randomUUID(),
    spiritEssence: randomUUID(),
  },

  // ── Item Templates: Boss Equipment ──────────────────────────────────────
  bossGear: {
    wolfsbaneBlade: randomUUID(),
    alphaPeltChest: randomUUID(),
    spiritStaff: randomUUID(),
    etherealRobes: randomUUID(),
  },

  // ── Item Templates: Mob Drop Materials ────────────────────────────────────
  drop: {
    ratPelt: randomUUID(),
    boarHide: randomUUID(),
    spiderSilk: randomUUID(),
    ratTail: randomUUID(),
    boarTusk: randomUUID(),
    wolfPelt: randomUUID(),
    banditCloth: randomUUID(),
    wolfFang: randomUUID(),
    ancientBark: randomUUID(),
    batWing: randomUUID(),
    goblinRag: randomUUID(),
    batFang: randomUUID(),
    stolenCoin: randomUUID(),
    crudeGemstone: randomUUID(),
    faeSilk: randomUUID(),
    dryadThread: randomUUID(),
    spriteDust: randomUUID(),
    pixieWing: randomUUID(),
    crawlerChitin: randomUUID(),
    roughGem: randomUUID(),
    stolenOre: randomUUID(),
    crystalShard: randomUUID(),
    wargHide: randomUUID(),
    harpyFeather: randomUUID(),
    harpyTalon: randomUUID(),
    crocHide: randomUUID(),
    hydraScale: randomUUID(),
    witchCloth: randomUUID(),
    wraithEssence: randomUUID(),
    boneFragment: randomUUID(),
    bogHeart: randomUUID(),
    cutGem: randomUUID(),
    goblinGold: randomUUID(),
    darkCrystal: randomUUID(),
    nagaScale: randomUUID(),
    spectralSilk: randomUUID(),
    oozeResidue: randomUUID(),
    eldritchFragment: randomUUID(),
    lichDust: randomUUID(),
    nagaPearl: randomUUID(),
    ancientRelic: randomUUID(),
  },

  // ── Item Templates: Processed Leather/Cloth ───────────────────────────────
  leather: {
    ratLeather: randomUUID(),
    boarLeather: randomUUID(),
    silkCloth: randomUUID(),
    wolfLeather: randomUUID(),
    batLeather: randomUUID(),
    wovenCloth: randomUUID(),
    wargLeather: randomUUID(),
    chitinPlate: randomUUID(),
    faeFabric: randomUUID(),
    crocLeather: randomUUID(),
    scaleMail: randomUUID(),
    cursedFabric: randomUUID(),
    etherealCloth: randomUUID(),
    nagaLeather: randomUUID(),
    spectralFabric: randomUUID(),
  },

  // ── Item Templates: Consumables ───────────────────────────────────────────
  pots: {
    minorHealthPotion: randomUUID(),
    healthPotion: randomUUID(),
    antivenomPotion: randomUUID(),
    greaterHealthPotion: randomUUID(),
    resistPotion: randomUUID(),
    manaPotion: randomUUID(),
    elixirOfPower: randomUUID(),
    minorStaminaPotion: randomUUID(),
    staminaPotion: randomUUID(),
    greaterStaminaPotion: randomUUID(),
    minorManaPotion: randomUUID(),
    greaterManaPotion: randomUUID(),
  },

  // ── Item Templates: Weapons ───────────────────────────────────────────────
  wep: {
    // Tier 1
    woodenSword: randomUUID(),
    oakShortbow: randomUUID(),
    oakStaff: randomUUID(),
    copperDagger: randomUUID(),
    // Tier 2
    tinSword: randomUUID(),
    mapleLongbow: randomUUID(),
    mapleStaff: randomUUID(),
    boarTuskMace: randomUUID(),
    batWingCrossbow: randomUUID(),
    goblinHexStaff: randomUUID(),
    // Tier 3
    ironLongsword: randomUUID(),
    willowWarbow: randomUUID(),
    elderwoodStaff: randomUUID(),
    crawlerFangBlade: randomUUID(),
    harpyTalonBow: randomUUID(),
    faeCrystalStaff: randomUUID(),
    // Tier 4
    darkIronGreatsword: randomUUID(),
    bogwoodLongbow: randomUUID(),
    crystalStaffWep: randomUUID(),
    hydraFangSabre: randomUUID(),
    wraithBow: randomUUID(),
    witchsSceptre: randomUUID(),
    // Tier 5
    mithrilBlade: randomUUID(),
    ancientBow: randomUUID(),
    lichStaff: randomUUID(),
  },

  // ── Item Templates: Armor ─────────────────────────────────────────────────
  // key = t{tier}_{weight}_{slot}
  arm: {
    // Tier 1 (head, chest)
    t1_heavy_head: randomUUID(),
    t1_heavy_chest: randomUUID(),
    t1_medium_head: randomUUID(),
    t1_medium_chest: randomUUID(),
    t1_light_head: randomUUID(),
    t1_light_chest: randomUUID(),
    // Tier 2 (head, chest, legs)
    t2_heavy_head: randomUUID(),
    t2_heavy_chest: randomUUID(),
    t2_heavy_legs: randomUUID(),
    t2_medium_head: randomUUID(),
    t2_medium_chest: randomUUID(),
    t2_medium_legs: randomUUID(),
    t2_light_head: randomUUID(),
    t2_light_chest: randomUUID(),
    t2_light_legs: randomUUID(),
    // Tier 3 (head, chest, legs, boots, gloves)
    t3_heavy_head: randomUUID(),
    t3_heavy_chest: randomUUID(),
    t3_heavy_legs: randomUUID(),
    t3_heavy_boots: randomUUID(),
    t3_heavy_gloves: randomUUID(),
    t3_medium_head: randomUUID(),
    t3_medium_chest: randomUUID(),
    t3_medium_legs: randomUUID(),
    t3_medium_boots: randomUUID(),
    t3_medium_gloves: randomUUID(),
    t3_light_head: randomUUID(),
    t3_light_chest: randomUUID(),
    t3_light_legs: randomUUID(),
    t3_light_boots: randomUUID(),
    t3_light_gloves: randomUUID(),
    // Tier 4 (head, chest, legs, boots, gloves, belt)
    t4_heavy_head: randomUUID(),
    t4_heavy_chest: randomUUID(),
    t4_heavy_legs: randomUUID(),
    t4_heavy_boots: randomUUID(),
    t4_heavy_gloves: randomUUID(),
    t4_heavy_belt: randomUUID(),
    t4_medium_head: randomUUID(),
    t4_medium_chest: randomUUID(),
    t4_medium_legs: randomUUID(),
    t4_medium_boots: randomUUID(),
    t4_medium_gloves: randomUUID(),
    t4_medium_belt: randomUUID(),
    t4_light_head: randomUUID(),
    t4_light_chest: randomUUID(),
    t4_light_legs: randomUUID(),
    t4_light_boots: randomUUID(),
    t4_light_gloves: randomUUID(),
    t4_light_belt: randomUUID(),
    // Tier 5 (all 6 slots)
    t5_heavy_head: randomUUID(),
    t5_heavy_chest: randomUUID(),
    t5_heavy_legs: randomUUID(),
    t5_heavy_boots: randomUUID(),
    t5_heavy_gloves: randomUUID(),
    t5_heavy_belt: randomUUID(),
    t5_medium_head: randomUUID(),
    t5_medium_chest: randomUUID(),
    t5_medium_legs: randomUUID(),
    t5_medium_boots: randomUUID(),
    t5_medium_gloves: randomUUID(),
    t5_medium_belt: randomUUID(),
    t5_light_head: randomUUID(),
    t5_light_chest: randomUUID(),
    t5_light_legs: randomUUID(),
    t5_light_boots: randomUUID(),
    t5_light_gloves: randomUUID(),
    t5_light_belt: randomUUID(),
  },

  // ── Item Templates: Jewellery ───────────────────────────────────────────────
  jewel: {
    // Rings (T1-T5)
    copperRing: randomUUID(),
    ironBand: randomUUID(),
    darkIronRing: randomUUID(),
    mithrilRing: randomUUID(),
    ancientRing: randomUUID(),
    // Necklaces (T1-T5)
    copperPendant: randomUUID(),
    ironChain: randomUUID(),
    darkIronAmulet: randomUUID(),
    mithrilNecklace: randomUUID(),
    ancientAmulet: randomUUID(),
    // Charms (T1-T5)
    copperCharm: randomUUID(),
    ironTalisman: randomUUID(),
    darkIronCharm: randomUUID(),
    mithrilTalisman: randomUUID(),
    ancientCharm: randomUUID(),
  },

  // ── Item Templates: Advanced (Soulbound) Gear ─────────────────────────────
  adv: {
    ratHideGloves: randomUUID(),
    spiderSilkBelt: randomUUID(),
    boarHideBoots: randomUUID(),
    wolfFangNecklace: randomUUID(),
    banditsLuckyRing: randomUUID(),
    ironbarkGloves: randomUUID(),
    batWingBoots: randomUUID(),
    goblinTrinketCharm: randomUUID(),
    spriteDustRing: randomUUID(),
    faeCrown: randomUUID(),
    heartwoodShield: randomUUID(),
    crystalCoreBelt: randomUUID(),
    chitinGauntlets: randomUUID(),
    wargRiderBelt: randomUUID(),
    warlordsSignet: randomUUID(),
    windcallersCharm: randomUUID(),
    deathKnightsRing: randomUUID(),
    hydraScaleShield: randomUUID(),
    covenAmulet: randomUUID(),
    stormCrystalCharm: randomUUID(),
    diamondGolemBelt: randomUUID(),
    goblinKingsCrown: randomUUID(),
  },

  // ── Mob Templates ─────────────────────────────────────────────────────────
  mobs: {
    // Forest Edge
    forestRat: randomUUID(),
    fieldMouse: randomUUID(),
    giantRat: randomUUID(),
    ratKing: randomUUID(),
    forestSpider: randomUUID(),
    webSpinner: randomUUID(),
    venomousSpider: randomUUID(),
    broodMother: randomUUID(),
    wildBoar: randomUUID(),
    tuskedBoar: randomUUID(),
    greatBoar: randomUUID(),
    // Deep Forest
    youngWolf: randomUUID(),
    forestWolf: randomUUID(),
    direWolf: randomUUID(),
    alphaWolf: randomUUID(),
    woodlandBandit: randomUUID(),
    banditScout: randomUUID(),
    banditEnforcer: randomUUID(),
    banditCaptain: randomUUID(),
    twigBlight: randomUUID(),
    barkGolem: randomUUID(),
    darkTreant: randomUUID(),
    elderTreant: randomUUID(),
    // Ancient Grove
    forestSprite: randomUUID(),
    wisp: randomUUID(),
    dryad: randomUUID(),
    ancientSpirit: randomUUID(),
    darkTreantGrove: randomUUID(),
    mossGolem: randomUUID(),
    ancientTreant: randomUUID(),
    treantPatriarch: randomUUID(),
    pixieSwarm: randomUUID(),
    thornFairy: randomUUID(),
    faeKnight: randomUUID(),
    faeQueen: randomUUID(),
    // Cave Entrance
    caveRat: randomUUID(),
    cavernBeetle: randomUUID(),
    giantCaveSpider: randomUUID(),
    ratMatriarch: randomUUID(),
    caveBat: randomUUID(),
    direBat: randomUUID(),
    vampireBat: randomUUID(),
    batSwarmLord: randomUUID(),
    goblin: randomUUID(),
    goblinArcher: randomUUID(),
    goblinWarrior: randomUUID(),
    goblinShaman: randomUUID(),
    // Deep Mines
    goblinMiner: randomUUID(),
    goblinSapper: randomUUID(),
    goblinForeman: randomUUID(),
    goblinChieftain: randomUUID(),
    clayGolem: randomUUID(),
    stoneGolem: randomUUID(),
    ironGolem: randomUUID(),
    crystalGolemMob: randomUUID(),
    rockCrawler: randomUUID(),
    caveLurker: randomUUID(),
    burrower: randomUUID(),
    tunnelWyrm: randomUUID(),
    // Whispering Plains
    plainsWolf: randomUUID(),
    coyote: randomUUID(),
    warg: randomUUID(),
    packAlpha: randomUUID(),
    highwayBandit: randomUUID(),
    banditArcherPlains: randomUUID(),
    banditLieutenant: randomUUID(),
    banditWarlord: randomUUID(),
    harpy: randomUUID(),
    harpyScout: randomUUID(),
    harpyWindcaller: randomUUID(),
    harpyMatriarch: randomUUID(),
    // Haunted Marsh
    skeleton: randomUUID(),
    zombie: randomUUID(),
    wraith: randomUUID(),
    deathKnight: randomUUID(),
    bogToad: randomUUID(),
    marshCrawlerMob: randomUUID(),
    swampHydra: randomUUID(),
    ancientCrocodile: randomUUID(),
    hagServant: randomUUID(),
    cursedVillager: randomUUID(),
    bogWitch: randomUUID(),
    covenMother: randomUUID(),
    // Crystal Caverns
    goblinGemHunter: randomUUID(),
    goblinTunneler: randomUUID(),
    goblinArtificer: randomUUID(),
    goblinKingMob: randomUUID(),
    crystalGolemCav: randomUUID(),
    gemConstruct: randomUUID(),
    diamondGolemMob: randomUUID(),
    golemOverlord: randomUUID(),
    shardElemental: randomUUID(),
    crystalWispMob: randomUUID(),
    stormCrystalMob: randomUUID(),
    crystalTitan: randomUUID(),
    // Sunken Ruins
    drownedSailor: randomUUID(),
    skeletalKnight: randomUUID(),
    spectralCaptain: randomUUID(),
    lich: randomUUID(),
    seaSnake: randomUUID(),
    marshViper: randomUUID(),
    nagaWarrior: randomUUID(),
    nagaQueenMob: randomUUID(),
    ooze: randomUUID(),
    tentacleHorror: randomUUID(),
    fleshGolem: randomUUID(),
    eldritchAbomination: randomUUID(),
  },
};

export type SeedIds = typeof IDS;
