export interface ZoneFlavorData {
  arrivalText: string;
  ambientTexts: { [key: string]: string };
  environmentalTexts: Record<string, string>;
}

export const ZONE_FLAVOR_TEXT: Record<string, ZoneFlavorData> = {
  'Millbrook': {
    arrivalText: 'The road narrows, the trees thin, and there it is: Millbrook. A cluster of timber-framed buildings at the point where farmland meets forest, smelling of woodsmoke and fresh bread and just a little bit of manure. It is not much. But it is yours, for now.',
    ambientTexts: {
      morning: 'Sunlight slants across the cobblestones as shutters bang open along the main street. A blacksmith\'s hammer rings out in steady rhythm. Somewhere, a rooster crows for the third time, and someone throws a boot at it.',
      afternoon: 'The market square hums with low commerce. Farmers argue over grain prices. A pair of apprentice crafters compare burn marks with quiet pride. The smell of the tavern\'s midday stew drifts through every open door, persistent as a rumor.',
      evening: 'Lanterns flicker to life along the main road. The tavern fills. Returning adventurers swap stories that grow taller with each telling, while merchants count the day\'s take and the town guard leans against the gate, watching the treeline.',
      night: 'Millbrook goes quiet, but never quite silent. Crickets fill the dark. The forge\'s coals glow dull orange through the smithy window. Somewhere past the gate, something shrieks in the Forest Edge, and no one looks up from their drink.',
    },
    environmentalTexts: {
      'The Main Street': 'A dirt road paved with ambition and about twelve yards of actual cobblestone. Stalls line both sides: general goods to the left, a weapons rack to the right, and the ever-present smell of tanning leather from the workshop out back.',
      'The Town Square': 'A modest clearing with a well at its center, perpetually surrounded by people who are definitely about to get water and not just standing around gossiping. A cork notice board by the well posts bounties, warnings, and one very persistent advertisement for singing lessons.',
      'The Crafting Quarter': 'Three workshops crowd together behind the tavern. The forge, the tannery, and an alchemist\'s bench that occasionally emits sounds that make the neighbors nervous. Apprentices are welcome. Explosions are not, but they happen anyway.',
      'The Gate': 'A wooden palisade with a single gate facing the Forest Edge. It looks sturdy enough to discourage anything up to the size of a large boar. Anything bigger, and the town\'s defence strategy shifts to "hope and distance." A guard is usually posted here. Usually.',
      'The Tavern (The Crooked Antler)': 'The oldest building in Millbrook, identifiable by its sagging roofline and the antler mounted above the door that hasn\'t hung straight since anyone can remember. Inside: warm light, cheap ale, and the comfortable noise of people pretending the wilderness beyond the walls is someone else\'s problem.',
    },
  },

  'Forest Edge': {
    arrivalText: 'The gate closes behind you with a thud that feels more final than it should. Ahead, the forest begins: dappled sunlight, birdsong, and the faint rustle of things that have been watching you since you stepped outside. The path is well-worn. That is either reassuring or a warning, depending on your disposition.',
    ambientTexts: {
      early: 'Sunlight filters through the oak canopy in shifting columns. The undergrowth is thick but navigable, and the air smells of damp earth and crushed herbs. Something chittered in the bushes a moment ago. It has gone quiet now, which is arguably worse.',
      mid: 'The trees grow closer together here, and the paths fork without signage. Spider silk catches the light between branches. Copper-streaked stones jut from the hillside where the soil has eroded. A boar snorts somewhere to your left, unseen but very much present.',
      deep: 'The canopy thickens overhead. Less sunlight reaches the forest floor, and the undergrowth gives way to moss and root. Webs stretch between the lower trunks in sheets. The chittering has been replaced by a heavier sound: something large, shifting its weight in the shadows ahead.',
      after_combat: 'The forest settles back into its rhythms quickly. Birds resume singing. Insects hum. Whatever you just killed will be scavenged before nightfall. The Forest Edge wastes nothing.',
    },
    environmentalTexts: {
      'The Treeline': 'Where farmland ends and the forest begins. From Millbrook\'s gate, you can see exactly where the neat rows of crops give way to wild undergrowth. Farmers maintain a cleared strip between their fields and the trees. Nothing grows there. Nothing is allowed to.',
      'Copper Hollows': 'A stretch of shallow ravines where copper ore veins run close to the surface. The soil here has a greenish tint, and the stones leave rusty smudges on your hands. Miners from Millbrook work these deposits in shifts, always in pairs, always watching the treeline.',
      'The Old Woodcutting Trail': 'A muddy track winding through the oaks, marked by fresh stumps and the drag marks of hauled logs. Woodcutters have been working this trail for generations. The trees keep growing back, thicker each time, as if the forest is trying to make a point.',
      'Silk Hollows': 'A low-lying area where the spiders are thickest. Webs hang between every trunk like wet laundry, and the air has a faintly sweet, chemical smell. Weavers from Millbrook come here to harvest silk with long poles and short tempers. The spiders tolerate this about as well as you would expect.',
      'The Sage Patches': 'Scattered clearings where Forest Sage grows in dense, knee-high clusters. The herb\'s peppery scent keeps most vermin at bay, which makes these clearings some of the only places in the Forest Edge where you can sit down without checking for rats first. Foragers guard their favourite patches jealously.',
    },
  },

  'Deep Forest': {
    arrivalText: 'The canopy closes overhead like a door you did not ask to be shut. Sunlight becomes suggestion, filtering through layers of leaf and branch in thin, unreliable shafts. The birdsong from the Forest Edge fades behind you, replaced by something quieter: the creak of old wood, the drip of condensation, and the low, thoughtful silence of things that hunt by listening.',
    ambientTexts: {
      early: 'The trees here are older and thicker, their trunks wrapped in moss and their roots tangled across the path like tripwires laid by something with a poor sense of humour. The air is cool, damp, and heavy with the smell of rotting leaves. You can still see the sky if you crane your neck. That will change.',
      mid: 'The undergrowth thins where the canopy blocks out the sun entirely. Pale mushrooms grow in clusters along fallen trunks. Wolf tracks cross the path in pairs, recent enough that the mud has not yet filled them. Somewhere deeper in, a branch snaps with the sharp crack of something heavy shifting its weight.',
      deep: 'No sunlight reaches the forest floor here. The air smells of moss and damp bark and, faintly, woodsmoke from a fire you cannot see. The trees loom like pillars in a cathedral nobody built on purpose. Shapes move between them: too deliberate to be wind, too slow to be prey.',
      after_combat: 'Blood soaks into the mulch and vanishes. The forest absorbs everything eventually. Somewhere overhead, a crow calls once, then falls silent. You are being watched, but that is nothing new. It has been true since you arrived.',
    },
    environmentalTexts: {
      'The Old Road': 'A trade route that once connected Millbrook to settlements further north, now overgrown and half-reclaimed by root and vine. Stone mile markers still stand at intervals, their carvings worn smooth by weather and neglect. Bandits favour the stretches where the road narrows between steep banks.',
      'Tin Ridge': 'A low, rocky escarpment where tin ore veins run close to the surface, staining the stone a dull grey-blue. The mining is harder here than at the Forest Edge\'s copper hollows; the ore is deeper, the creatures are meaner, and the ridge has a habit of crumbling underfoot at inconvenient moments.',
      'The Maple Stands': 'Groves of old-growth maple, their trunks broader than a man\'s arm span. Woodcutters from Millbrook rarely venture this deep, preferring to hire adventurers to haul logs back along the Old Road. The wood is prized for bows and staves, and the trees do not appreciate being harvested. Some of them express this sentiment personally.',
      'Moonpetal Glades': 'Small clearings where Moonpetal flowers grow in pale, luminous clusters that glow faintly after dark. Foragers tread carefully here; the glades attract both the flowers and the things that feed on the insects drawn to their light. Wolves use the clearings as hunting grounds. So do the bandits.',
      'The Wolf Runs': 'Narrow game trails carved through the undergrowth by generations of wolf packs. The trails are efficient, well-maintained, and absolutely not intended for human use. Following one is the fastest way to cross the Deep Forest. It is also the fastest way to find wolves, which is the same thing said less optimistically.',
    },
  },

  'Cave Entrance': {
    arrivalText: 'The forest floor drops away and there it is: a cavern mouth wide enough to swallow a house, breathing out a slow, cold exhalation that smells of wet stone and something older. The daylight ends abruptly at the threshold, as if it took one look inside and decided not to follow you. Somewhere in the dark, water drips in a rhythm that is almost, but not quite, regular.',
    ambientTexts: {
      early: 'The entrance tunnel slopes gently downward, its walls slick with condensation. Pale mushrooms cluster along the base of the walls, casting a faint bioluminescent glow that is just bright enough to make the shadows worse. Rat droppings litter the floor. Something squeaks in the dark and falls silent.',
      mid: 'The ceiling opens up into a vaulted chamber studded with old tin deposits, their veins catching your torchlight in dull metallic flashes. Fungal growths cling to the support timbers left by miners who worked here decades ago. The timbers are rotting. The fungus is thriving. Nature has its priorities.',
      deep: 'The tunnels branch and narrow. Bat guano coats the floor in patches, and the air carries a sour, acidic tang. Crude markings appear on the walls: goblin scratches, angular and deliberate, pointing deeper into the cave system. They might be warnings. They might be directions. With goblins, the distinction is mostly academic.',
      after_combat: 'The echoes take a long time to die in here. Your breathing sounds louder than it should, and the dripping resumes the moment the fighting stops, as if the cave was waiting politely for you to finish.',
    },
    environmentalTexts: {
      'The Maw': 'The cavern entrance itself, a limestone arch draped in ivy and dark moss. Old mining carts sit rusted on their rails near the threshold, one of them overturned and colonized by cave moss. A faded sign reads "Holloway Mining Co." in paint that has mostly surrendered to the elements. Whether there is a connection to Bram Holloway at the general store is a question nobody in Millbrook answers directly.',
      'The Tin Galleries': 'Upper chambers where tin ore veins run through the limestone in dark, glittering seams. The miners who abandoned these tunnels left their picks embedded in the walls, and some of the deposits are half-extracted, interrupted mid-swing. Whatever drove the miners out, it happened quickly.',
      'The Fungal Corridors': 'Narrow passages where pale, woody fungal growths have consumed the old support timbers and spread across the walls and ceiling. The "wood" harvested here is not wood at all, but dense fungal matter with similar properties. It smells of damp earth and tastes of regret, according to the one Millbrook carpenter who tried eating it.',
      'The Bat Roosts': 'High-ceilinged chambers where colonies of bats hang in dense, rustling clusters from the stalactites. The floor below is thick with guano, which foragers collect as a component in certain alchemical processes that polite society pretends do not exist. Disturbing a roost is inadvisable. The bats do not appreciate it, and there are more of them than there are of you.',
      'The Goblin Warrens': 'Deeper tunnels marked by crude torches, scratched walls, and the unmistakable smell of something cooking badly. The goblins have claimed these passages as their own, and their presence is evident in the scattered debris, the occasional trap (usually sprung, occasionally not), and the distant sound of arguing in a language that consists primarily of consonants.',
    },
  },

  'Ancient Grove': {
    arrivalText: 'The Deep Forest opens, and something changes. The air grows warmer. The light shifts from grey-green to gold, filtering through a canopy so high and so dense that it feels less like a ceiling and more like a second sky. The trees here are enormous, their trunks wider than buildings, their roots raised above the soil like the ribs of something buried. Nothing about this place feels accidental. You have stepped into a forest that remembers being planted, and it has opinions about visitors.',
    ambientTexts: {
      early: 'Motes of light drift between the trunks, too slow and too deliberate to be dust. The undergrowth is sparse; instead, soft moss carpets the ground in shades of green that do not occur naturally anywhere else. The silence is not the predatory quiet of the Deep Forest. It is the silence of a place that is listening and has decided, for now, to let you continue.',
      mid: 'The elderwood trees grow closer together here, their branches intertwined overhead like clasped hands. Faint sounds reach you: laughter that might be wind, footsteps that might be settling bark, whispers in a language you almost understand. Starbloom flowers glow in pale clusters at the base of the oldest trunks, pulsing gently, as if breathing.',
      deep: 'The grove\'s heart. The trees here are alive in the way that most trees are not: deliberately, watchfully, with roots that shift when you are not looking. Spirits drift between the trunks as pale, luminous shapes, and the fae court holds somewhere in the canopy above, visible only as flashes of colour and the occasional sound of something laughing at you specifically.',
      after_combat: 'The grove absorbs violence the way a pond absorbs a stone: a ripple, a pause, then stillness. The moss has already begun to cover the marks of the fight. The trees lean in, just slightly, as if curious about the outcome. You won. They noticed. Whether that is approval or assessment is impossible to say.',
    },
    environmentalTexts: {
      'The Elder Ring': 'A circle of the oldest elderwood trees in the grove, their trunks so massive that the spaces between them form natural archways. The bark is silver-grey and warm to the touch. Woodcutters who have harvested elderwood from the outer grove say these trees are different. They are. Touching one produces a low hum that you feel in your chest rather than hear. Nobody harvests from the Elder Ring. Not twice.',
      'The Starbloom Meadow': 'A clearing where Starbloom flowers grow in dense constellations, their petals translucent and faintly luminous even in daylight. At night (or what passes for night under the canopy), they glow like fallen stars. Foragers tread carefully here; the flowers are rooted in soil saturated with ambient magic, and the things that feed on that magic tend to be territorial, beautiful, and sharp.',
      'The Spirit Paths': 'Faint trails of residual light that wind between the elderwoods, visible only at certain angles. Spirits travel along these paths in slow processions, and the air above them shimmers with residual warmth. Crossing a spirit path is not dangerous, exactly, but it draws attention. The spirits notice you the way a river notices a stone: they flow around you, and something in their passage leaves you feeling examined.',
      'The Canopy Court': 'High above the forest floor, where the elderwood branches weave together into platforms and walkways, the fae have built something between a palace and a nest. You cannot reach it from below (they made sure of that), but you can see flashes of colour, hear fragments of music, and occasionally feel something small and sharp bounce off your head. The fae do not throw things at people they dislike. They throw things at everyone. It is a cultural practice.',
      'The Sanctum': 'The deepest chamber of the grove, where the Ancient Spirit dwells. The air here is thick with magic, visible as a faint golden haze that clings to everything. The elderwoods have grown together to form a natural cathedral, and at its centre, something very old and very powerful watches, and waits, and occasionally decides to remind visitors why this place is called sacred.',
    },
  },

  'Deep Mines': {
    arrivalText: 'The goblin tunnels end and the old mine shafts begin, and you can tell the difference because the goblins built for utility and the miners built for greed. The ceilings vault higher here, braced by iron beams that were forged to last and have nearly managed it. Rails run along the floor in rusted pairs, leading deeper into a darkness that your torch illuminates but does not dispel. The sign at the first junction reads "Holloway Deep Shaft: Authorized Personnel Only." The definition of "authorized" has changed since it was posted.',
    ambientTexts: {
      early: 'The upper shafts still bear the marks of organized industry: pick scars on the walls in neat rows, numbered junctions, and the occasional ore cart abandoned mid-load. The iron beams groan softly overhead. Glowcap mushrooms have colonized the damp corners, casting a sickly yellow-green light that flickers when something disturbs the air.',
      mid: 'Deeper. The organized shafts give way to rougher passages where the miners followed the ore veins wherever they led. The walls glitter with iron deposits, exposed and untouched since the day the picks stopped swinging. Something heavy drags itself through a parallel tunnel, just out of sight. The sound of stone grinding on stone follows you like a patient thought.',
      deep: 'The mine has been swallowed. Goblin construction presses in from the sides: crude supports, stacked rubble, and the ammonia reek of explosives stored badly. Golem husks stand in alcoves, some intact, some crumbling, all watching with empty sockets. The crawlers have burrowed through the floors, creating a labyrinth of collapsed passages and unstable ground. You are not exploring the Deep Mines anymore. You are navigating what is left of them.',
      after_combat: 'Dust settles in the torchlight. The echoes bounce through the shafts for seconds after the fighting ends, each repetition fainter and more distorted until the silence returns. The mine remembers every sound. That is the problem with fighting underground: nothing is ever truly over until the echoes say it is.',
    },
    environmentalTexts: {
      'The Holloway Shafts': 'The original mining complex, built by whoever established Holloway Mining Co. and abandoned under circumstances nobody in Millbrook discusses openly. The shafts are numbered, well-braced, and still structurally sound in most places. Iron ore veins run through the walls in thick, dark seams, richer than anything at the surface. The miners knew what they had. They left anyway.',
      'The Iron Galleries': 'Deep chambers where the richest iron deposits sit exposed in cathedral-like formations. The ore here is high-grade, dark, and heavy with potential. Kessa Ironweld calls Deep Mines iron "the good stuff," and the weapons forged from it bear her out. Mining here is productive but perilous; the golems that formed from the deposit walls do not appreciate the competition.',
      'The Glowcap Caverns': 'Low-ceilinged grottos where Glowcap Mushrooms grow in dense, luminous clusters on every surface. The light they emit is greenish-gold and strangely warm, creating pockets of visibility in the otherwise total darkness. Vesper Tain considers them one of the most versatile alchemical ingredients in the Pocketrealm. She also considers the caves they grow in "absolutely not worth the trip," which is why she pays adventurers to bring them back instead.',
      'The Goblin Undercity': 'Below the mine\'s lowest level, the goblins have excavated their own settlement: a chaotic warren of tunnels, chambers, and structural crimes against engineering. Torches burn in sconces made from stolen ore carts. Crude furniture clutters rooms that were never designed to be rooms. The goblins here are miners too, after a fashion. They mine what the humans left, and what they cannot mine, they steal from each other.',
      'The Crawlerways': 'A web of narrow, organic tunnels bored through the stone by the crawlers that infest the mine\'s deepest levels. The walls are smooth and slightly warm, polished by the passage of chitin and acid. Following a crawlerway is the fastest route between shafts, and also the fastest way to encounter something with more legs than you and fewer reservations about using them.',
    },
  },

  'Whispering Plains': {
    arrivalText: 'The trees end. All of them, all at once, as if the forest reached a line it was not willing to cross. Beyond it: grass. An ocean of it, waist-high and rippling under a wind that has not stopped since before you were born. The sky is enormous here, wider than anything you have seen since leaving Millbrook, and the horizon stretches in every direction without a single landmark to anchor it. The wind carries sounds from far away. Some of them are cries. Some of them are warnings. Out here, the difference is academic.',
    ambientTexts: {
      early: 'The grass parts around you in waves, closing behind as if you were never here. The wind is constant, warm, and carries the smell of wild herbs and dry earth. Sandstone outcrops jut from the plain at intervals, their surfaces worn smooth by weather and time. Something moves through the grass to your left, low and fast. It could be a wolf. It could be the wind. You cannot tell, and that is the point.',
      mid: 'The grass grows taller here, above your head in places, and the wind creates corridors of flattened stalks that shift and close without pattern. Willow trees cluster along dry riverbeds, their branches trailing in the wind like long, pale fingers. Bandit camps hide in the shallow ravines between hills, visible only by the thin trails of smoke they cannot quite suppress.',
      deep: 'The plains open into vast, treeless stretches where the sky dominates everything. Shadows pass overhead: harpies, circling on thermals with the lazy patience of something that can see you from a mile away and is in no hurry. The wind here carries voices, fragments of words in no language you recognize. Whether the whispering is the wind itself or something using the wind as a carrier is a question best left unanswered.',
      after_combat: 'The grass straightens. The wind fills the silence where the fighting was. In minutes, the plain will look as if nothing happened here. The Whispering Plains do not keep records. They keep moving.',
    },
    environmentalTexts: {
      'The Grasslands': 'Endless. The grass itself is a tough, blue-green variety that grows year-round and bends without breaking under the constant wind. Rowan Delk says the plains grass is the hardiest plant in the Pocketrealm, which is high praise from a man who rarely praises anything that is not ore-bearing.',
      'The Sandstone Ridges': 'Low, weathered formations of pale orange sandstone that break the flatness in clusters. The stone is softer than cave rock but dense enough for Cut Stone, a crafting material that Kessa uses for whetstones and reinforcement. Mining here means working in the open, exposed to wind, wolves, and whatever else is watching from the grass.',
      'The Willow Runs': 'Dry riverbeds lined with weeping willows whose roots tap water tables far below the surface. The wood is flexible, resilient, and prized for bows (the Willow Warbow is crafted from it). Woodcutting here is peaceful in a way that Deep Forest woodcutting is not. The willows do not fight back. The things hiding among them, however, might.',
      'The Windbloom Fields': 'Patches of pale blue flowers that grow only on the windward side of the sandstone ridges, where the constant breeze carries their pollen in spiralling columns. Windbloom is a foraging herb used in stamina restoration. Its petals are thin as paper and taste like cold mint. Gathering it in high wind is an exercise in patience and swearing.',
      'The Harpy Thermals': 'Open stretches where warm air rises from sun-baked stone, creating updrafts that the harpies ride for hours without a single wingbeat. From below, they look like dark crosses against the sky. From above (their perspective), you look like lunch. The thermals are a natural landmark: where the harpies circle, the hunting is good. For them.',
    },
  },

  'Thornwall': {
    arrivalText: 'You have been walking for long enough that the Whispering Plains stopped feeling vast and started feeling personal, so when the walls appear on the horizon, the relief is physical. Thornwall. A settlement built like a clenched fist: high stone walls, iron-banded gates, and the kind of architecture that says "we have been attacked before and we did not enjoy it." It is not welcoming. It is something better. It is standing.',
    ambientTexts: {
      morning: 'The gates open at first light, and the main road fills with the sound of industry. Hammers ring from workshops that dwarf Millbrook\'s Crafting Quarter. The smell is different here: less woodsmoke, more hot metal and quenching oil. A patrol returns through the eastern gate, armour dented, saying nothing. Nobody asks how the night went. The answer is always the same.',
      afternoon: 'The market is smaller than Millbrook\'s but sharper. No farmers arguing over grain prices here; just crafters selling advanced gear, alchemists measuring dark iron reagents, and adventurers comparing scars with the quiet competitiveness of people who know that scars are the only r\u00e9sum\u00e9 that matters.',
      evening: 'The casino lights up as the workshops wind down, and for a brief, improbable hour, Thornwall sounds almost festive. Silas Vane\'s roulette wheel clicks in the background. Somewhere, someone wins big and someone loses bigger, and both of them will be back tomorrow because Thornwall is the kind of place where you either gamble or you stare at the walls, and the walls stare back.',
      night: 'Thornwall does not sleep so much as lower its voice. The walls are manned at all hours. Torches gutter along the battlements, and the guards watch the darkness beyond with the focused attention of people who know exactly what lives out there. From the Haunted Marsh to the south, something howls. From the Crystal Caverns below, something hums. Thornwall ignores both with practiced discipline.',
    },
    environmentalTexts: {
      'The Main Road': 'A broad, cobbled avenue running from the western gate (where you entered) to the eastern gate (where the patrols go). Workshops and vendors line both sides, their signs advertising services that Millbrook has never heard of: dark iron smelting, crystal wood lathing, advanced enchantment. The road is clean, maintained, and lit by iron lanterns that burn with a steadiness suggesting either good engineering or minor magic.',
      'The Forge District': 'Thornwall\'s crafting facilities are not a quarter; they are a district. Multiple forges, each specializing in different materials and techniques, operate side by side in a long hall that vents smoke through stone chimneys tall enough to be visible from the plains. The maxCraftingLevel here is, effectively, unlimited. If the material exists, someone in the Forge District can work it. Whether they will work it for you depends on what you bring them.',
      'The Eastern Gate': 'Where the patrols leave and, ideally, return. The gate faces the approaches to the Haunted Marsh, the Crystal Caverns, and the Sunken Ruins. The stonework around it is noticeably thicker than the western gate, reinforced with dark iron brackets and scored by old claw marks that nobody has bothered to smooth out. They are left as a reminder, or possibly a warning, or possibly because the masonry budget ran out.',
      'The Casino (The Gilded Wheel)': 'A stone-fronted building on the main road\'s south side, identifiable by the gold-painted wheel above the entrance and the faint sound of clinking coins that escapes whenever the door opens. Silas Vane runs the roulette table here with the quiet authority of a man who has turned probability into a career. Inside: warm light, expensive drinks, and the comfortable sound of people making decisions they will regret in the morning.',
      'The Thornwall Barracks': 'A squat, functional building behind the eastern gate where the town\'s patrol squads rest between rotations. The barracks are not open to adventurers, but the noticeboard outside posts warnings about current threats, creature sightings, and the occasional recruitment notice for volunteer patrols. The pay is bad. The mortality rate is suggestive. Volunteers are welcome.',
      'The Supply Depot': 'A reinforced warehouse near the western gate where frontier merchants stock advanced materials, rare reagents, and equipment that Millbrook\'s vendors cannot source. Prices are higher here because the supply chains are longer, the materials are better, and the merchants have survived the trip to get them here, which they consider worth a premium.',
    },
  },

  'Haunted Marsh': {
    arrivalText: 'The ground softens under your boots, then squelches, then tries to keep them. The air thickens with the smell of decay: not the clean rot of a forest floor but the slow, wet dissolution of things that should have stayed buried. Mist clings to the surface of black water, and somewhere beneath it, something shifts. The Haunted Marsh does not welcome visitors. It tolerates them, briefly, the way a predator tolerates prey that has not yet noticed where it is standing.',
    ambientTexts: {
      early: 'The marsh begins as soggy grassland, ankle-deep in brackish water that reflects a sky it should not be able to see through the mist. Dead trees stand at odd angles, their bark stripped white by moisture and time. Bog toads croak from unseen perches. The ground bubbles occasionally, releasing pockets of gas that smell like something you should not have been able to identify and wish you could not.',
      mid: 'Deeper. The water rises to your knees, and the ground beneath it becomes unreliable: solid stone one step, bottomless silt the next. Dark iron deposits jut from the muck in corroded veins, staining the water rust-red where they surface. Bogwood trunks lie half-submerged, their surfaces slick with something that is not moss and not mould and is best left unexamined. The mist has closed behind you. Thornwall\'s walls are no longer visible, and the sun is a rumour.',
      deep: 'The marsh becomes a labyrinth of stagnant channels and sunken islands. The dead walk here: skeletons rising from the mud with the unhurried patience of things that have nowhere else to be. The witches\' territory begins at the thorn hedges that grow from the water itself, marking boundaries that the swamp\'s other inhabitants know better than to cross. The air tastes of iron and old magic, and the mist has begun to glow faintly, lit from below by something you do not want to find.',
      after_combat: 'The marsh fills the silence the way water fills a footprint: slowly, completely, without opinion. The mist settles back. The dead return to the mud, or do not, depending on how thoroughly you dealt with them. Nothing here stays dead reliably. That is the problem with the Haunted Marsh. It remembers.',
    },
    environmentalTexts: {
      'The Shallows': 'Where the Whispering Plains give way to standing water and the grass turns from blue-green to grey-brown to dead. The transition is gradual enough that you are waist-deep before you realise you have entered the marsh proper. Thornwall\'s eastern patrols mark the boundary with iron stakes. The stakes rust within weeks. They replace them anyway.',
      'The Iron Mires': 'Stretches of rust-coloured water where dark iron ore veins surface through the mud in thick, corroded seams. The ore is high-grade but extracting it means standing knee-deep in water that is cold, foul, and occasionally inhabited. Miners work in pairs here, one digging and one watching. The watching is considered the harder job.',
      'The Bogwood Groves': 'Stands of dead and dying trees whose wood has been preserved by the marsh\'s chemistry into something darker, denser, and more resilient than any living timber. Bogwood does not rot. Gavrik Stoneshoulder says this is because even decay has standards. Harvesting it means wading into territory that the swamp beasts consider theirs, and their definition of "theirs" is expansive.',
      'The Gravemoss Banks': 'Low, spongy mounds where Gravemoss grows in thick, grey-green carpets. The moss smells of damp earth and something medicinal, and Vesper Tain considers it essential for her Resist Potion formula. It grows best on the banks where the dead have been buried, which is either a coincidence or the marsh\'s idea of humour. Nobody laughs.',
      'The Coven Hollows': 'Sunken clearings deep in the marsh where the witches have made their homes: crude huts of woven thorn and stretched hide, surrounded by bone chimes and the acrid smoke of whatever they are brewing. The hollows are difficult to find, which is by design, and more difficult to leave, which is also by design.',
      'The Bonefields': 'A vast, shallow expanse where the marsh\'s bottom is carpeted with the remains of things that died here and were not allowed to stay dead. Bones surface through the mud in tangled heaps, and the skeletons that rise from them do so with a familiarity that suggests they have done this before. Gavrik lost his hand here. The memorial wall in Thornwall has three names from this stretch alone.',
    },
  },

  'Crystal Caverns': {
    arrivalText: 'The Deep Mines descend, and then they change. The rough-hewn stone gives way to something polished, faceted, and glowing with its own light. The Crystal Caverns do not need your torch. They are luminous in the way that deep water is luminous: from within, without explanation, and with the faint suggestion that the light is paying attention to you rather than the other way around. The air hums. Not wind, not vibration, but a resonance that you feel in your sternum and your fillings. The caverns are beautiful. That is, historically, a very bad sign.',
    ambientTexts: {
      early: 'The upper chambers are vast and vaulted, their walls studded with crystal formations that refract your torchlight into constellations. Mithril veins thread through the stone like silver capillaries, and crystal wood grows from cracks in the floor: pale, translucent stalks that are not quite plant and not quite mineral. Everything glitters. The effect is breathtaking, and the breathing is what gives you away to the things that live here.',
      mid: 'Deeper, the crystals grow larger and more irregular, jutting from walls and ceiling in clusters that hum at different frequencies. The harmonics overlap, creating a constant, low chord that Vesper would call beautiful and you would call distracting. Goblin tunnels intersect the natural passages here, their crude excavations scarring the crystal walls. Golem shapes stand in the shadows, indistinguishable from the formations they were made from until the light shifts.',
      deep: 'The caverns open into cathedral-scale chambers where the crystals have grown together into pillars, arches, and formations that look disturbingly intentional. The light down here is not refracted torch glow; it is generated by the crystals themselves, pulsing in slow, rhythmic waves that match no known natural cycle. Shard elementals drift through the air like living geometry. The hum has become a chord, and the chord has become a song, and the song is very old and does not care whether you know the words.',
      after_combat: 'Shattered crystal rains down from the ceiling where a stray blow struck the wall. The fragments glow for a moment, then dim. The caverns absorb violence the way they absorb everything else: slowly, luminously, and with a patience that suggests they were here before the fighting started and will be here long after it stops.',
    },
    environmentalTexts: {
      'The Mithril Veins': 'Silver-white ore that runs through the crystal walls in delicate, branching patterns, as if the stone grew a circulatory system. Mithril is the most valuable mining resource in the Pocketrealm, and the caverns hold more of it than any surface deposit. Kessa Ironweld calls it "the only metal worth losing sleep over." Extracting it from crystal-embedded stone requires precision, patience, and a willingness to work in a place where the walls hum and the golems watch.',
      'The Crystal Groves': 'Sections where crystal wood has taken root in the cavern floor, growing in translucent stands that resemble frozen trees. The "wood" is crystallised plant matter, rigid and resonant, prized for staves and bows that channel magic with unusual clarity. Cutting it produces a tone, and each stalk produces a different one. Woodcutters describe the process as "performing surgery on a wind chime."',
      'The Shimmer Fern Grottos': 'Sheltered alcoves where Shimmer Fern grows in luminous clusters, its fronds casting a soft blue light that makes the surrounding crystals glow in response. The fern\'s active compounds are used in Mana Potion brewing, and Vesper considers the cavern-grown variety superior to any surface specimen. She also considers the journey to reach them "a meaningful argument against the advancement of science."',
      'The Goblin King\'s Hall': 'Deep in the caverns, where the goblins have carved their most ambitious settlement into the crystal walls. The throne room glitters with embedded gems and smelted ore. The hall is both a political centre and a military stronghold, and the Goblin King rules from it with an authority that the caverns\' other inhabitants grudgingly acknowledge.',
      'The Resonance Chamber': 'A natural amphitheatre at the caverns\' heart where the crystal formations have grown into a structure that amplifies and harmonises the ambient hum into something almost musical. The elementals congregate here, drawn by the energy. The Crystal Titan (the elemental boss) claims this chamber as its domain, and the resonance intensifies to a visible shimmer in its presence. Standing in the chamber feels like standing inside a thought.',
    },
  },

  'Sunken Ruins': {
    arrivalText: 'The passage descends through flooded stone and into something older than the mines, older than the caves, older than anything above ground has a right to be. The Sunken Ruins were a city once. You can tell by the columns, the archways, and the carved friezes that line the walls above the waterline, depicting scenes in a language nobody alive can read. The water is black, cold, and shin-deep at the entrance. It gets deeper. Everything here gets deeper. The air smells of brine and age and something underneath both that your instincts recognise before your mind does. You are not the first person to come here. You might, with effort and luck, be one of the few who leaves.',
    ambientTexts: {
      early: 'The upper halls are half-submerged, their floors tilted at angles that suggest the entire structure shifted at some point in the distant past and nobody was left to correct it. Columns rise from the water at drunken angles, their surfaces encrusted with barnacles and pale growth. The light here comes from bioluminescent algae clinging to the walls, casting everything in a sickly blue-green wash that makes shadows look deeper than they are. They might not be deeper than they look. It is hard to tell, and harder to want to check.',
      mid: 'The ruins deepen into flooded galleries where the water reaches your waist and the ceiling drops low enough to brush your head. Ancient ore veins run through the walls in dark, heavy seams, embedded in stone that was carved long before anyone thought to mine it. Petrified wood beams support archways that were old when Millbrook was a campfire. Something large moved through the water ahead of you. The ripples have not settled.',
      deep: 'The deepest chambers are fully submerged in places, forcing you through neck-deep corridors of black water and blind corners. The ruins here are better preserved, paradoxically: sealed from the elements by the water that destroyed the upper levels. The carvings on the walls are intact, and they depict things that Vesper Tain would study for years and Aldric Voss would file under "do not open." The abominations make their nests here, in the dark places where the water is warm and the stone whispers.',
      after_combat: 'The water clouds with silt and worse. The echoes of the fight bounce through the flooded corridors for what feels like minutes, distorted and multiplied until it sounds like the ruins themselves are repeating what happened, learning the shape of the violence. The bioluminescence dims, then returns. The water stills. The Sunken Ruins do not forget. They add everything to their collection.',
    },
    environmentalTexts: {
      'The Drowned Galleries': 'The upper chambers of the ruins, half-flooded and half-collapsed, where the architecture is still recognisable as architecture. Columns, archways, and vaulted ceilings speak to a civilisation that built for permanence and achieved it, in the worst way possible. Whatever lived here is gone. What moved in afterwards is not.',
      'The Ancient Ore Deposits': 'Veins of Ancient Ore, the rarest mining material in the Pocketrealm, embedded in the ruins\' structural stone. The ore is dark, impossibly dense, and warm to the touch regardless of the water\'s chill. Kessa Ironweld has never worked it in person; she works from ingots that adventurers bring back, and she treats each one with a reverence she shows nothing else. The ore was here before the city. The city was built around it. That says something about priorities.',
      'The Petrified Groves': 'Sections where trees (or what were once trees) grew through the ruins\' floors and were preserved by centuries of mineral-rich saltwater into crystallised stone. The petrified wood is the densest, hardest wood-equivalent in the Pocketrealm, and cutting it produces a tone so deep you feel it in your bones rather than hear it. The Ancient Bow is carved from this material, and its silence when fired is a reflection of the silence that created it.',
      'The Kelp Forests': 'Submerged chambers where Abyssal Kelp grows in thick, dark curtains from ceiling to floor, swaying in currents that have no visible source. The kelp is essential for the Elixir of Power, and Vesper Tain describes it as "the single most potent natural reagent in existence, growing in the single worst place to collect it." Foraging here means diving blind into kelp-choked water where serpents hunt and abominations nest. The kelp does not make it easier. It hides everything.',
      'The Throne Hall': 'The deepest, most intact chamber in the ruins: a vast, pillared hall with a raised dais at its far end, still bearing the outline of a throne that has long since dissolved into the water. The carvings here are the most detailed and the most disturbing, depicting rituals and entities that belong to a chapter of the Pocketrealm\'s history that was not so much forgotten as deliberately erased. The Lich and the Eldritch Abomination contest this space, and neither acknowledges the other\'s claim.',
    },
  },
};
