-- Backfill the zone-specific chest reward rows introduced with the chest
-- crafting rebalance. Seed changes alone do not update existing databases.

CREATE TEMP TABLE "_zone_chest_reward_backfill" (
  "family_name" TEXT NOT NULL,
  "zone_name" TEXT NOT NULL,
  "chest_rarity" TEXT NOT NULL,
  "item_name" TEXT NOT NULL,
  "chance_pct" INTEGER NOT NULL,
  "min_quantity" INTEGER NOT NULL,
  "max_quantity" INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO "_zone_chest_reward_backfill"
  ("family_name", "zone_name", "chest_rarity", "item_name", "chance_pct", "min_quantity", "max_quantity")
VALUES
  ('Bandits', 'Deep Forest', 'common', 'Bandit Cloth', 100, 3, 5),
  ('Bandits', 'Deep Forest', 'common', 'Stolen Coin', 25, 1, 2),
  ('Bandits', 'Deep Forest', 'common', 'Crude Gemstone', 15, 1, 1),
  ('Bandits', 'Deep Forest', 'common', 'Health Potion', 20, 1, 1),
  ('Bandits', 'Deep Forest', 'uncommon', 'Bandit Cloth', 95, 5, 8),
  ('Bandits', 'Deep Forest', 'uncommon', 'Stolen Coin', 30, 2, 4),
  ('Bandits', 'Deep Forest', 'uncommon', 'Crude Gemstone', 45, 1, 2),
  ('Bandits', 'Deep Forest', 'uncommon', 'Health Potion', 35, 1, 1),
  ('Bandits', 'Deep Forest', 'rare', 'Bandit Cloth', 95, 8, 14),
  ('Bandits', 'Deep Forest', 'rare', 'Stolen Coin', 35, 3, 7),
  ('Bandits', 'Deep Forest', 'rare', 'Crude Gemstone', 55, 2, 4),
  ('Bandits', 'Deep Forest', 'rare', 'Health Potion', 45, 1, 2),
  ('Bandits', 'Deep Forest', 'epic', 'Bandit Cloth', 100, 12, 18),
  ('Bandits', 'Deep Forest', 'epic', 'Stolen Coin', 40, 4, 8),
  ('Bandits', 'Deep Forest', 'epic', 'Crude Gemstone', 65, 3, 5),
  ('Bandits', 'Deep Forest', 'epic', 'Health Potion', 55, 2, 3),
  ('Bandits', 'Deep Forest', 'legendary', 'Bandit Cloth', 100, 15, 22),
  ('Bandits', 'Deep Forest', 'legendary', 'Stolen Coin', 45, 5, 10),
  ('Bandits', 'Deep Forest', 'legendary', 'Crude Gemstone', 70, 4, 7),
  ('Bandits', 'Deep Forest', 'legendary', 'Health Potion', 60, 3, 5),

  ('Bandits', 'Whispering Plains', 'common', 'Bandit Cloth', 100, 3, 5),
  ('Bandits', 'Whispering Plains', 'common', 'Stolen Coin', 30, 1, 3),
  ('Bandits', 'Whispering Plains', 'common', 'Crude Gemstone', 15, 1, 1),
  ('Bandits', 'Whispering Plains', 'common', 'Health Potion', 20, 1, 1),
  ('Bandits', 'Whispering Plains', 'uncommon', 'Bandit Cloth', 95, 5, 9),
  ('Bandits', 'Whispering Plains', 'uncommon', 'Stolen Coin', 35, 2, 5),
  ('Bandits', 'Whispering Plains', 'uncommon', 'Crude Gemstone', 45, 1, 3),
  ('Bandits', 'Whispering Plains', 'uncommon', 'Health Potion', 35, 1, 1),
  ('Bandits', 'Whispering Plains', 'rare', 'Bandit Cloth', 95, 9, 15),
  ('Bandits', 'Whispering Plains', 'rare', 'Stolen Coin', 40, 3, 7),
  ('Bandits', 'Whispering Plains', 'rare', 'Crude Gemstone', 55, 2, 4),
  ('Bandits', 'Whispering Plains', 'rare', 'Health Potion', 45, 1, 2),
  ('Bandits', 'Whispering Plains', 'epic', 'Bandit Cloth', 100, 12, 19),
  ('Bandits', 'Whispering Plains', 'epic', 'Stolen Coin', 45, 4, 8),
  ('Bandits', 'Whispering Plains', 'epic', 'Crude Gemstone', 65, 3, 5),
  ('Bandits', 'Whispering Plains', 'epic', 'Health Potion', 55, 2, 3),
  ('Bandits', 'Whispering Plains', 'legendary', 'Bandit Cloth', 100, 16, 24),
  ('Bandits', 'Whispering Plains', 'legendary', 'Stolen Coin', 50, 5, 10),
  ('Bandits', 'Whispering Plains', 'legendary', 'Crude Gemstone', 70, 4, 7),
  ('Bandits', 'Whispering Plains', 'legendary', 'Health Potion', 60, 3, 5),

  ('Wolves', 'Deep Forest', 'common', 'Wolf Pelt', 75, 2, 3),
  ('Wolves', 'Deep Forest', 'common', 'Wolf Fang', 45, 1, 2),
  ('Wolves', 'Deep Forest', 'common', 'Health Potion', 20, 1, 1),
  ('Wolves', 'Deep Forest', 'uncommon', 'Wolf Pelt', 85, 4, 6),
  ('Wolves', 'Deep Forest', 'uncommon', 'Wolf Fang', 65, 3, 5),
  ('Wolves', 'Deep Forest', 'uncommon', 'Health Potion', 35, 1, 1),
  ('Wolves', 'Deep Forest', 'rare', 'Wolf Pelt', 90, 6, 10),
  ('Wolves', 'Deep Forest', 'rare', 'Wolf Fang', 75, 4, 7),
  ('Wolves', 'Deep Forest', 'rare', 'Health Potion', 45, 1, 2),
  ('Wolves', 'Deep Forest', 'epic', 'Wolf Pelt', 95, 8, 14),
  ('Wolves', 'Deep Forest', 'epic', 'Wolf Fang', 85, 6, 10),
  ('Wolves', 'Deep Forest', 'epic', 'Health Potion', 55, 2, 3),
  ('Wolves', 'Deep Forest', 'legendary', 'Wolf Pelt', 100, 10, 16),
  ('Wolves', 'Deep Forest', 'legendary', 'Wolf Fang', 90, 7, 12),
  ('Wolves', 'Deep Forest', 'legendary', 'Health Potion', 60, 3, 5),

  ('Wolves', 'Whispering Plains', 'common', 'Warg Hide', 70, 2, 3),
  ('Wolves', 'Whispering Plains', 'common', 'Wolf Fang', 40, 1, 2),
  ('Wolves', 'Whispering Plains', 'common', 'Wolf Pelt', 25, 1, 2),
  ('Wolves', 'Whispering Plains', 'common', 'Greater Health Potion', 15, 1, 1),
  ('Wolves', 'Whispering Plains', 'uncommon', 'Warg Hide', 85, 4, 6),
  ('Wolves', 'Whispering Plains', 'uncommon', 'Wolf Fang', 55, 2, 4),
  ('Wolves', 'Whispering Plains', 'uncommon', 'Wolf Pelt', 35, 2, 3),
  ('Wolves', 'Whispering Plains', 'uncommon', 'Greater Health Potion', 30, 1, 1),
  ('Wolves', 'Whispering Plains', 'rare', 'Warg Hide', 95, 6, 10),
  ('Wolves', 'Whispering Plains', 'rare', 'Wolf Fang', 65, 3, 5),
  ('Wolves', 'Whispering Plains', 'rare', 'Wolf Pelt', 40, 3, 4),
  ('Wolves', 'Whispering Plains', 'rare', 'Greater Health Potion', 40, 1, 2),
  ('Wolves', 'Whispering Plains', 'epic', 'Warg Hide', 100, 8, 14),
  ('Wolves', 'Whispering Plains', 'epic', 'Wolf Fang', 75, 4, 7),
  ('Wolves', 'Whispering Plains', 'epic', 'Wolf Pelt', 45, 4, 6),
  ('Wolves', 'Whispering Plains', 'epic', 'Greater Health Potion', 50, 2, 3),
  ('Wolves', 'Whispering Plains', 'legendary', 'Warg Hide', 100, 10, 16),
  ('Wolves', 'Whispering Plains', 'legendary', 'Wolf Fang', 80, 5, 9),
  ('Wolves', 'Whispering Plains', 'legendary', 'Wolf Pelt', 50, 5, 8),
  ('Wolves', 'Whispering Plains', 'legendary', 'Greater Health Potion', 55, 3, 5),

  ('Fae', 'Ancient Grove', 'common', 'Fae Silk', 70, 2, 3),
  ('Fae', 'Ancient Grove', 'common', 'Pixie Wing', 35, 1, 2),
  ('Fae', 'Ancient Grove', 'common', 'Greater Health Potion', 20, 1, 1),
  ('Fae', 'Ancient Grove', 'uncommon', 'Fae Silk', 85, 4, 7),
  ('Fae', 'Ancient Grove', 'uncommon', 'Pixie Wing', 55, 2, 4),
  ('Fae', 'Ancient Grove', 'uncommon', 'Greater Health Potion', 35, 1, 1),
  ('Fae', 'Ancient Grove', 'uncommon', 'Focused Mana Potion', 25, 1, 1),
  ('Fae', 'Ancient Grove', 'rare', 'Fae Silk', 95, 6, 10),
  ('Fae', 'Ancient Grove', 'rare', 'Pixie Wing', 65, 3, 5),
  ('Fae', 'Ancient Grove', 'rare', 'Greater Health Potion', 45, 1, 2),
  ('Fae', 'Ancient Grove', 'rare', 'Focused Mana Potion', 35, 1, 1),
  ('Fae', 'Ancient Grove', 'epic', 'Fae Silk', 100, 8, 14),
  ('Fae', 'Ancient Grove', 'epic', 'Pixie Wing', 75, 4, 7),
  ('Fae', 'Ancient Grove', 'epic', 'Greater Health Potion', 55, 2, 3),
  ('Fae', 'Ancient Grove', 'epic', 'Focused Mana Potion', 45, 2, 3),
  ('Fae', 'Ancient Grove', 'legendary', 'Fae Silk', 100, 10, 16),
  ('Fae', 'Ancient Grove', 'legendary', 'Pixie Wing', 80, 5, 9),
  ('Fae', 'Ancient Grove', 'legendary', 'Greater Health Potion', 60, 3, 5),
  ('Fae', 'Ancient Grove', 'legendary', 'Focused Mana Potion', 50, 3, 5),

  ('Undead', 'Haunted Marsh', 'common', 'Wraith Essence', 65, 2, 3),
  ('Undead', 'Haunted Marsh', 'common', 'Bone Fragment', 55, 2, 3),
  ('Undead', 'Haunted Marsh', 'common', 'Resist Potion', 20, 1, 1),
  ('Undead', 'Haunted Marsh', 'uncommon', 'Wraith Essence', 80, 4, 6),
  ('Undead', 'Haunted Marsh', 'uncommon', 'Bone Fragment', 75, 4, 7),
  ('Undead', 'Haunted Marsh', 'uncommon', 'Resist Potion', 35, 1, 1),
  ('Undead', 'Haunted Marsh', 'rare', 'Wraith Essence', 90, 6, 10),
  ('Undead', 'Haunted Marsh', 'rare', 'Bone Fragment', 85, 6, 10),
  ('Undead', 'Haunted Marsh', 'rare', 'Resist Potion', 45, 1, 2),
  ('Undead', 'Haunted Marsh', 'epic', 'Wraith Essence', 95, 8, 14),
  ('Undead', 'Haunted Marsh', 'epic', 'Bone Fragment', 90, 8, 14),
  ('Undead', 'Haunted Marsh', 'epic', 'Resist Potion', 55, 2, 3),
  ('Undead', 'Haunted Marsh', 'legendary', 'Wraith Essence', 100, 10, 16),
  ('Undead', 'Haunted Marsh', 'legendary', 'Bone Fragment', 95, 10, 16),
  ('Undead', 'Haunted Marsh', 'legendary', 'Resist Potion', 60, 3, 5),

  ('Undead', 'Sunken Ruins', 'common', 'Spectral Silk', 65, 2, 3),
  ('Undead', 'Sunken Ruins', 'common', 'Lich Dust', 20, 1, 1),
  ('Undead', 'Sunken Ruins', 'common', 'Wraith Essence', 35, 1, 2),
  ('Undead', 'Sunken Ruins', 'common', 'Elixir of Power', 15, 1, 1),
  ('Undead', 'Sunken Ruins', 'uncommon', 'Spectral Silk', 80, 4, 6),
  ('Undead', 'Sunken Ruins', 'uncommon', 'Lich Dust', 35, 1, 2),
  ('Undead', 'Sunken Ruins', 'uncommon', 'Wraith Essence', 45, 2, 3),
  ('Undead', 'Sunken Ruins', 'uncommon', 'Elixir of Power', 25, 1, 1),
  ('Undead', 'Sunken Ruins', 'rare', 'Spectral Silk', 90, 6, 10),
  ('Undead', 'Sunken Ruins', 'rare', 'Lich Dust', 50, 2, 3),
  ('Undead', 'Sunken Ruins', 'rare', 'Wraith Essence', 55, 3, 5),
  ('Undead', 'Sunken Ruins', 'rare', 'Elixir of Power', 35, 1, 2),
  ('Undead', 'Sunken Ruins', 'epic', 'Spectral Silk', 95, 8, 14),
  ('Undead', 'Sunken Ruins', 'epic', 'Lich Dust', 65, 3, 5),
  ('Undead', 'Sunken Ruins', 'epic', 'Wraith Essence', 60, 4, 7),
  ('Undead', 'Sunken Ruins', 'epic', 'Elixir of Power', 45, 2, 3),
  ('Undead', 'Sunken Ruins', 'legendary', 'Spectral Silk', 100, 10, 16),
  ('Undead', 'Sunken Ruins', 'legendary', 'Lich Dust', 75, 4, 7),
  ('Undead', 'Sunken Ruins', 'legendary', 'Wraith Essence', 65, 5, 9),
  ('Undead', 'Sunken Ruins', 'legendary', 'Elixir of Power', 55, 3, 5),

  ('Swamp Beasts', 'Haunted Marsh', 'common', 'Croc Hide', 70, 2, 3),
  ('Swamp Beasts', 'Haunted Marsh', 'common', 'Hydra Scale', 40, 1, 2),
  ('Swamp Beasts', 'Haunted Marsh', 'common', 'Bog Heart', 25, 1, 1),
  ('Swamp Beasts', 'Haunted Marsh', 'common', 'Resist Potion', 20, 1, 1),
  ('Swamp Beasts', 'Haunted Marsh', 'uncommon', 'Croc Hide', 85, 4, 6),
  ('Swamp Beasts', 'Haunted Marsh', 'uncommon', 'Hydra Scale', 60, 2, 4),
  ('Swamp Beasts', 'Haunted Marsh', 'uncommon', 'Bog Heart', 45, 1, 3),
  ('Swamp Beasts', 'Haunted Marsh', 'uncommon', 'Resist Potion', 35, 1, 1),
  ('Swamp Beasts', 'Haunted Marsh', 'rare', 'Croc Hide', 95, 6, 10),
  ('Swamp Beasts', 'Haunted Marsh', 'rare', 'Hydra Scale', 75, 4, 6),
  ('Swamp Beasts', 'Haunted Marsh', 'rare', 'Bog Heart', 55, 2, 4),
  ('Swamp Beasts', 'Haunted Marsh', 'rare', 'Resist Potion', 45, 1, 2),
  ('Swamp Beasts', 'Haunted Marsh', 'epic', 'Croc Hide', 100, 8, 14),
  ('Swamp Beasts', 'Haunted Marsh', 'epic', 'Hydra Scale', 85, 5, 8),
  ('Swamp Beasts', 'Haunted Marsh', 'epic', 'Bog Heart', 65, 3, 5),
  ('Swamp Beasts', 'Haunted Marsh', 'epic', 'Resist Potion', 55, 2, 3),
  ('Swamp Beasts', 'Haunted Marsh', 'legendary', 'Croc Hide', 100, 10, 16),
  ('Swamp Beasts', 'Haunted Marsh', 'legendary', 'Hydra Scale', 90, 6, 10),
  ('Swamp Beasts', 'Haunted Marsh', 'legendary', 'Bog Heart', 70, 4, 7),
  ('Swamp Beasts', 'Haunted Marsh', 'legendary', 'Resist Potion', 60, 3, 5),

  ('Goblins', 'Crystal Caverns', 'common', 'Goblin Gold', 60, 2, 3),
  ('Goblins', 'Crystal Caverns', 'common', 'Cut Gem', 40, 1, 2),
  ('Goblins', 'Crystal Caverns', 'common', 'Crude Gemstone', 35, 1, 2),
  ('Goblins', 'Crystal Caverns', 'common', 'Mithril Ore', 35, 1, 2),
  ('Goblins', 'Crystal Caverns', 'common', 'Greater Mana Potion', 15, 1, 1),
  ('Goblins', 'Crystal Caverns', 'uncommon', 'Goblin Gold', 75, 4, 6),
  ('Goblins', 'Crystal Caverns', 'uncommon', 'Cut Gem', 60, 2, 4),
  ('Goblins', 'Crystal Caverns', 'uncommon', 'Crude Gemstone', 45, 2, 3),
  ('Goblins', 'Crystal Caverns', 'uncommon', 'Mithril Ore', 50, 2, 4),
  ('Goblins', 'Crystal Caverns', 'uncommon', 'Greater Mana Potion', 30, 1, 1),
  ('Goblins', 'Crystal Caverns', 'rare', 'Goblin Gold', 85, 6, 10),
  ('Goblins', 'Crystal Caverns', 'rare', 'Cut Gem', 75, 3, 5),
  ('Goblins', 'Crystal Caverns', 'rare', 'Crude Gemstone', 55, 3, 4),
  ('Goblins', 'Crystal Caverns', 'rare', 'Mithril Ore', 60, 3, 6),
  ('Goblins', 'Crystal Caverns', 'rare', 'Greater Mana Potion', 40, 1, 2),
  ('Goblins', 'Crystal Caverns', 'epic', 'Goblin Gold', 95, 8, 14),
  ('Goblins', 'Crystal Caverns', 'epic', 'Cut Gem', 85, 4, 7),
  ('Goblins', 'Crystal Caverns', 'epic', 'Crude Gemstone', 60, 4, 6),
  ('Goblins', 'Crystal Caverns', 'epic', 'Mithril Ore', 70, 4, 8),
  ('Goblins', 'Crystal Caverns', 'epic', 'Greater Mana Potion', 50, 2, 3),
  ('Goblins', 'Crystal Caverns', 'legendary', 'Goblin Gold', 100, 10, 16),
  ('Goblins', 'Crystal Caverns', 'legendary', 'Cut Gem', 90, 5, 9),
  ('Goblins', 'Crystal Caverns', 'legendary', 'Crude Gemstone', 65, 5, 8),
  ('Goblins', 'Crystal Caverns', 'legendary', 'Mithril Ore', 75, 5, 10),
  ('Goblins', 'Crystal Caverns', 'legendary', 'Greater Mana Potion', 55, 3, 5),

  ('Golems', 'Crystal Caverns', 'common', 'Dark Crystal', 60, 2, 3),
  ('Golems', 'Crystal Caverns', 'common', 'Cut Gem', 35, 1, 2),
  ('Golems', 'Crystal Caverns', 'common', 'Crystal Shard', 35, 1, 2),
  ('Golems', 'Crystal Caverns', 'common', 'Mithril Ore', 45, 2, 3),
  ('Golems', 'Crystal Caverns', 'common', 'Greater Mana Potion', 15, 1, 1),
  ('Golems', 'Crystal Caverns', 'uncommon', 'Dark Crystal', 75, 4, 6),
  ('Golems', 'Crystal Caverns', 'uncommon', 'Cut Gem', 55, 2, 4),
  ('Golems', 'Crystal Caverns', 'uncommon', 'Crystal Shard', 45, 2, 4),
  ('Golems', 'Crystal Caverns', 'uncommon', 'Mithril Ore', 65, 3, 6),
  ('Golems', 'Crystal Caverns', 'uncommon', 'Greater Mana Potion', 30, 1, 1),
  ('Golems', 'Crystal Caverns', 'rare', 'Dark Crystal', 90, 6, 10),
  ('Golems', 'Crystal Caverns', 'rare', 'Cut Gem', 70, 3, 5),
  ('Golems', 'Crystal Caverns', 'rare', 'Crystal Shard', 50, 3, 5),
  ('Golems', 'Crystal Caverns', 'rare', 'Mithril Ore', 80, 5, 8),
  ('Golems', 'Crystal Caverns', 'rare', 'Greater Mana Potion', 40, 1, 2),
  ('Golems', 'Crystal Caverns', 'epic', 'Dark Crystal', 100, 8, 14),
  ('Golems', 'Crystal Caverns', 'epic', 'Cut Gem', 80, 4, 7),
  ('Golems', 'Crystal Caverns', 'epic', 'Crystal Shard', 55, 4, 7),
  ('Golems', 'Crystal Caverns', 'epic', 'Mithril Ore', 90, 6, 10),
  ('Golems', 'Crystal Caverns', 'epic', 'Greater Mana Potion', 50, 2, 3),
  ('Golems', 'Crystal Caverns', 'legendary', 'Dark Crystal', 100, 10, 16),
  ('Golems', 'Crystal Caverns', 'legendary', 'Cut Gem', 85, 5, 9),
  ('Golems', 'Crystal Caverns', 'legendary', 'Crystal Shard', 60, 5, 8),
  ('Golems', 'Crystal Caverns', 'legendary', 'Mithril Ore', 95, 7, 12),
  ('Golems', 'Crystal Caverns', 'legendary', 'Greater Mana Potion', 55, 3, 5);

DELETE FROM "chest_drop_tables" AS cdt
USING (
  SELECT DISTINCT "family_name", "zone_name", "chest_rarity"
  FROM "_zone_chest_reward_backfill"
) AS target,
"mob_families" AS mf,
"zones" AS z
WHERE mf."name" = target."family_name"
  AND z."name" = target."zone_name"
  AND cdt."mob_family_id" = mf."id"
  AND cdt."zone_id" = z."id"
  AND cdt."chest_rarity" = target."chest_rarity";

INSERT INTO "chest_drop_tables"
  ("id", "mob_family_id", "zone_id", "chest_rarity", "item_template_id", "drop_chance", "min_quantity", "max_quantity")
SELECT
  'zone-chest-v2:' || mf."id" || ':' || z."id" || ':' || rows."chest_rarity" || ':' || it."id",
  mf."id",
  z."id",
  rows."chest_rarity",
  it."id",
  (rows."chance_pct"::DECIMAL / 100)::DECIMAL(5, 4),
  rows."min_quantity",
  rows."max_quantity"
FROM "_zone_chest_reward_backfill" AS rows
JOIN "mob_families" AS mf
  ON mf."name" = rows."family_name"
JOIN "zones" AS z
  ON z."name" = rows."zone_name"
JOIN "item_templates" AS it
  ON it."name" = rows."item_name"
  AND it."season_id" IS NOT DISTINCT FROM z."season_id";

DELETE FROM "chest_drop_tables" AS cdt
USING "item_templates" AS it
WHERE cdt."item_template_id" = it."id"
  AND it."name" IN ('Bat Fang', 'Ooze Residue', 'Ancient Relic');

DROP TABLE "_zone_chest_reward_backfill";
